### PR TITLE
Polyester somelinkfixes

### PR DESCRIPTION
**Pull request by polyester**
Fixes: a few broken links to (old) plone.org

Improves:

Changes proposed in this pull request:
## 
## 
##

### CODE REVIEW

**Comment by polyester** [comment]
can be merged already, when checks pass, but please leave branch; I'll try to fix more and more between other jobs over the next few days

**Comment by svx** [comment]
I will wait with merging, I would like to push a new build next weekend [5/6 of June], cause I would like to fix some more stuff first, do you think that is enough time for you ?

@mauritsvanrees sorry for delaying for one week !

**Comment by polyester** [comment]
leaving for Poland on the 4th, I'll try...

**Comment by svx** [comment]
@polyester What is the status here ?

**Comment by polyester** [comment]
let's merge, I will create a new branch when needed

**Comment by svx** [comment]
Needs to be picked into 5.1

**Comment by polyester** [comment]
🍒👌

**Pull request merged**
