### PR TITLE
Unify style for console usage

### PR DESCRIPTION
**Pull request by svx**
- unify 'look and feel' for console usage

### CODE REVIEW

**Comment by jensens** [comment]
In my opinion the leading `$` is not very copy-paste friendly and I always hated it when I saw that used in documentation.

**Comment by svx** [comment]
@jensens I see you point, even if I think different, we have currently a mix in our docs.
I want to get rid of this confusing mix.

Even if it is not perfect, this is still one common way in documentation to make clear that this part of docs is a command.

This is not something I came up with, I even asked lots of friends from wtd, if its sane to use. 

Even if it may less user-friendly for copy and paste, it still has IMHO a value for the visual factor of docs, which is as important, because it helps people to understand.

**Comment by jensens** [comment]
Maybe I'am overall wrong and readability is more important.
But at least it makes copy-paste an annoying experience. 
So maybe we have here a +1 in readability and a -1 in usability.
Just my opinion as a user, I'am not a good doc-writer.

**Comment by polyester** [comment]
I have a question on this as well. It feels wrong to manually add a $ to a code-block; the whole point of unifying on a single recommendation for   `.. code-block:: console` is that Sphinx and CSS then take care of all visual clues that this is a command. Even if that means putting a "$" as background sprite before the command.

If that is not clear enough, then our CSS needs updating, but manually adding characters in front of a command is probably not the way to go, it mixes content with layout.

**Comment by svx** [comment]
https://pypi.python.org/pypi/sphinx-prompt/1.0.0 and other add-ons changing the background and adding a $ out of the box.

As I mentioned before I 'just' tried to unify the docs, because we use with $ and without $ through all the docs and that is even worse.

Sometimes it is really hard to stay motivated ... just saying .....

**Comment by jensens** [comment]
yeah, sorry if I brought in stop energy here :/

**Comment by polyester** [comment]
@svx, the effort is _hugely_ appreciated. And, as said, I'm all in favour of big visual clues to readers that something is a shell command. So, changing the background, and adding a (non-selectable) prompt is **good**. 

Just in this PR you are adding it in the _source_ RST files 'hard', where I think it should be the job of addons like sphinx-prompt or CSS to add those visual clues once it finds the `.. code-block:: console` directive.

So, no stop energy intended, but just trying to see if we do it the best way.

**Pull request closed without merging**
