### PR TITLE
Add documentation for browserlayer.xml

### PR DESCRIPTION
**Pull request by davilima6**

### CODE REVIEW

**Comment by svx** [comment]
@davilima6 thanks !

@jensens can I merge ?

**Comment by jensens** [comment]
Technically fine and very valuable. 

Naming - well - `product` vs. `addon` vs. `package`? What do we prefer? IIRC we want to get rid of the `products` in favor of `add-ons`? I can't remember in detail.

**Comment by polyester** [comment]
yes, we try to use add-ons (or addon, spelling is not clear in any dictionary). Products are _things you put in your hair, like shampoo_ to the US part of the audience.

**Comment by davilima6** [comment]
I updated the PR, and it's nice to know we have an official stand on this, but there are still lots of Product mentions in this file (not to say everywhere). Despite the neverending ocurrences of the Products namespace, we have as placeholders:
- your.package (most common by far)
- my.package
- project.policy
- gomobile.mobile
- betahaus.emaillogin
- collective.ducks
- collective.basket

If you'd like I can change all of them for `your.package`, or `your.addon` as this PR does right now.

**Comment by jensens** [comment]
if its referring technically to a python egg (the zip-file thing) I'd call it `your.package`. We could extend this to `your.addonpackage` to reduce confusion and build a bridge to the term add-on.

If we speak about it in sense of functionality only `add-on` is sufficient.

**Comment by davilima6** [comment]
In paragraphs (not code) the most common naming seems to be "add-on product" instead of "addon package". Once we decide this I'll make the replacements.

**Comment by svx** [comment]
I vote for "add-on package" @polyester ?

**Comment by davilima6** [comment]
Ok, so "add-on package" in paragraphs and "your.package" in examples? Or "your.addonpackage"?

**Comment by svx** [comment]
I would go with "your.addonpackage"

**Comment by polyester** [comment]
explicit is better than implicit: "your.addonpackage"

**Comment by davilima6** [comment]
OK, I updated this PR to follow the new suggestions. As soon as it is merged I'll replace the remaining occurrences.

**Comment by svx** [comment]
Thanks a lot !

**Pull request merged**
