### PR TITLE
Add warning not to create or activate a Python virtual environment

### PR DESCRIPTION
**Pull request by stevepiercy**
This affects 5 files.

See https://github.com/plone/cookieplone/issues/38

----
📚 Documentation preview 📚: https://plone6--1790.org.readthedocs.build/

### CODE REVIEW

**Review by davisagli — APPROVED** [review]

**Review by petschki — APPROVED** [review]

**Comment by stevepiercy** [comment]
List of affected files for review:

- [Install Plone with Cookieplone](https://plone6--1790.org.readthedocs.build//install/create-project-cookieplone.html#python)
- [Install Plone with Buildout](https://plone6--1790.org.readthedocs.build//admin-guide/install-buildout.html#python)
- [Install Plone with pip](https://plone6--1790.org.readthedocs.build//admin-guide/install-pip.html#python)
- [Install Plone with cookiecutter-plone-starter (deprecated)](https://plone6--1790.org.readthedocs.build/install/create-project.html#python)
- [Building and checking the quality of documentation](https://plone6--1790.org.readthedocs.build//contributing/documentation/setup-build.html#python)

**Comment by petschki** [comment]
Ah sorry ... I wasn't aware of the affected files. I think this warning only makes sense in the cookieplone doc because the other docs (pip, buildout) are later explaining in detail how to create a virtual environment for the installation on your own. Thats a bit confusing.

@davisagli what do you think?

**Comment by davisagli** [comment]
@petschki I'm not sure what happens if you have a virtualenv activated and then try to follow the pip or buildout install docs and create another virtualenv. Maybe it works out okay since the new virtualenv isn't activated, but that's why I thought it might be good to go ahead and add the warning for all of them.

**Comment by petschki** [comment]
Agreed ... better safe than sorry.

**Comment by stevepiercy** [comment]
I can change the warning for the one plone 6.0 include to remove "create or " and leave "activate", since we actually do say to create a virtual environment. Then it will make sense for the three files where it gets included. Follow up PR incoming.

**Pull request merged**
