### PR TITLE
Do3cc upgrade z3cform

### PR DESCRIPTION
**Pull request by do3cc**
Still unfinished but better than nothing.
Also, what got documented is right. I think ;-)

### CODE REVIEW

**Comment by do3cc** [comment]
Aww, damn, git merge does  work better for code than for docs, git does not understand that I created Control Panel Changes docs in september and somebody did the same in november. So don't merge, I need to check this manually

**Comment by do3cc** [comment]
This PR is not WIP any more
still need more docs though

**Comment by svx** [comment]
@do3cc do you mean it is OK to merge now or you want to wait and add more docs first ?

**Comment by do3cc** [comment]
Hi @svx I'd love to finish the documentation but I failed to do so since september. Since it is still a big improvement, I'm suggesting to merge it right now, because nobody looks for WIP pull requests when updating documentation

**Comment by svx** [comment]
ok !

**Pull request merged**
