### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by dbitouze**

### CODE REVIEW

**Review by stevepiercy — CHANGES_REQUESTED** [review]
Good catch! There are two other instances of `instance.yml` on this page. Would you please update them as well? Thank you!

**Comment by dbitouze** [comment]
> There are two other instances of `instance.yml` on this page. Would you please update them as well?

Done (if I'm not mistaken).

> Thank you!

You're welcome!

**Review by stevepiercy — APPROVED** [review]

**Comment by stevepiercy** [comment]
@dbitouze I'm sorry, but can you open up a PR from within this repo instead of your fork? I would like GitHub Actions to run, and that only happens from within this repo. Thank you!

**Comment by dbitouze** [comment]
> @dbitouze I'm sorry, but can you open up a PR from within this repo instead of your fork? I would like GitHub Actions to run, and that only happens from within this repo. Thank you!

I would be more than willing to do it if only I knew how to do it...

**Comment by stevepiercy** [comment]
@dbitouze have you signed the [Plone Contributor Agreement](https://plone.org/foundation/contributors-agreement)? Signatories may open PRs within the organization.

If not, please let me know, and I will just go ahead and merge this PR. IMO it is not a "creative work", and thus does not need to go through that process.

Of course, if you have not already signed the Plone CA, you are more than welcome to do so and become a fully fledged contributor to Plone, especially if you want to make "creative work" contributions.

**Comment by dbitouze** [comment]
> @dbitouze have you signed the [Plone Contributor Agreement](https://plone.org/foundation/contributors-agreement)?

No.

> Signatories may open PRs within the organization.

I see.

> If not, please let me know, and I will just go ahead and merge this PR.

Please proceed.

>IMO it is not a "creative work",

Surely not :smile: 

>  and thus does not need to go through that process.

Indeed.

> Of course, if you have not already signed the Plone CA, you are more than welcome to do so and become a fully fledged contributor to Plone, especially if you want to make "creative work" contributions.

I guess It is very unlikely for me to make “creative work” contributions on Plone since I'm a naïve user of it. And since my printer is currently out of order, I cannot fill the form.

**Comment by stevepiercy** [comment]
Done, and thank you!

**Pull request merged**
