### PR TITLE
Create skeleton framework for internationalization and localization

### PR DESCRIPTION
**Pull request by stevepiercy**
We want only content that has been thoroughly reviewed and approved in this PR. If the original content in the `i18n` directory is relevant, then it is fine to copy-paste. If not, then leave it out or fix it in the new skeleton framework files.

Fixes https://github.com/plone/documentation/issues/1267

Replaces https://github.com/plone/documentation/pull/1265

### CODE REVIEW

**Review by erral — APPROVED** [review]
I see this skeleton more than OK!

**Comment by erral** [comment]
@stevepiercy do you want me to provide the missing documentation on this branch or let's merge this and then provide specific PRs with the relevant docs?

**Comment by stevepiercy** [comment]
Either way is fine. Whatever is easiest for you to do the work.

**Comment by erral** [comment]
Ok, I will do it here.

**Comment by stevepiercy** [comment]
@erral please let me know when you would like me and others to review your work. I don't know if you can select me in the UI, because I am the original author and I don't think GitHub allows the author to review their own PR.

**Comment by erral** [comment]
@stevepiercy this is ready to be reviewed. I think I completed all the portions about multilinguality and so.

**Comment by stevepiercy** [comment]
Let's also get @jensens, @mauritsvanrees, and @ksuess a chance to review the technical details. I'll focus on English and MyST syntax and grammar.

**Comment by stevepiercy** [comment]
I decided to save some time and effort by making and pushing commits instead of a review using the GitHub UI. I only had time to look at `glossary.md` and `i18n-l10n/contributing-translations.md` this afternoon. I will work on the remaining files after dark.

**Review by jensens — APPROVED** [review]
This is great work!

**Review by mauritsvanrees — APPROVED** [review]
I have fixed two small typos.
LGTM. Thanks!

Is this ready for merge?  There are two todo markers in the code still. Could be handled later, there are more such markers in other parts of the documentation.

**Comment by stevepiercy** [comment]
At long last, I have completed my review. Changes include the usual English and MyST syntax fixes, but also some enhancements, such as screenshots, labels, glossary terms, and replacing `i18n` with `i18n-l10n`.

Could I please get one more round of reviews? @mauritsvanrees @erral @jensens @ksuess

**Review by erral — COMMENTED** [review]
I have seen 2 TO-DOs regarding the language control panel (one when p.a.multilingual is not installed, and the other one when configuring the translation policy to show "no content in your language"), I need to check both of them, but the rest is OK.

Thank you!

**Comment by mauritsvanrees** [comment]
You want to merge 111 commits with 91 changed files into the `add-i18n` branch. That is a tad much for a PR that claims to create a "skeleton framework". ;-)
I propose to remove the `add-i18n` branch (can be done later) and change this PR to target `6-dev` instead.

Also, is there no automated preview site anymore? I have been missing that for a while.

**Comment by stevepiercy** [comment]
@mauritsvanrees good point. The huge number of commits and file changes are the result of merging `6-dev` into this branch, which in retrospect I should not have done. Oopsie.

So I think I will go ahead and merge this PR. Then take the next step, open a PR of `add-i18n` into `6-dev`, which in turn will trigger a preview build. I'll go ahead and do that now, and that will make the review cleaner and easier.

**Pull request merged**
