### PR TITLE
Remove create, keep activate, in warning for Plone 6.0 docs.

### PR DESCRIPTION
**Pull request by stevepiercy**
----
📚 Documentation preview 📚: https://plone6--1791.org.readthedocs.build/

### CODE REVIEW

**Comment by stevepiercy** [comment]
@petschki @davisagli please wait for build to complete before approving. Thank you!

- [Install Plone with Buildout](https://plone6--1791.org.readthedocs.build//admin-guide/install-buildout.html#python)
- [Install Plone with pip](https://plone6--1791.org.readthedocs.build//admin-guide/install-pip.html#python)
- [Install Plone with cookiecutter-plone-starter (deprecated)](https://plone6--1791.org.readthedocs.build/install/create-project.html#python)

**Comment by stevepiercy** [comment]
Preview is built and ready for final review.

**Review by petschki — DISMISSED** [review]
OK for me ... though the sentences "Let the tools handle this for you. Additionally the commands in this guide use explicit paths to packages." do not really apply to pip and buildout installation, but for the deprecated cookiecutter installation its true ...

**Comment by stevepiercy** [comment]
> OK for me ... though the sentences "Let the tools handle this for you. Additionally the commands in this guide use explicit paths to packages." do not really apply to pip and buildout installation, but for the deprecated cookiecutter installation its true ...

What would be better? We have these commands for pip.

```shell
venv/bin/pip install -c https://dist.plone.org/release/6.0-latest/constraints.txt Plone pipx
bin/pipx run cookiecutter -f --no-input --config-file instance.yaml gh:plone/cookiecutter-zope-instance
bin/runwsgi -v instance/etc/zope.ini
```

and for buildout:

```shell
venv/bin/pip install -r https://dist.plone.org/release/6-latest/requirements.txt
venv/bin/buildout bootstrap
bin/buildout
bin/instance fg
bin/instance start
bin/instance stop
```

Maybe not "packages" but "binaries"?

**Comment by petschki** [comment]
Ah... now I know what this means. `explicit paths to binaries` makes much more sense to me.

**Comment by davisagli** [comment]
@stevepiercy @petschki Maybe the warning could be simplified to "Do not create or activate a Python virtual environment at this time. The instructions below will create one."

**Comment by stevepiercy** [comment]
@petschki @davisagli done in https://github.com/plone/documentation/pull/1791/commits/9e08ce1b997faa654e4355fefed4203212742fa0

**Review by davisagli — APPROVED** [review]

**Review by petschki — APPROVED** [review]

**Comment by stevepiercy** [comment]
The link was a transient failure, and works now. Merging. Thank you!

**Pull request merged**
