### PR TITLE
Update workflow actions

### PR DESCRIPTION
**Pull request by fredvd**
use cache for python setup
remove not existing matrix variables
update deprecated set-output

### CODE REVIEW

**Review by ksuess — APPROVED** [review]
LGTM. 
Cool! Thank you!

**Review by davisagli — APPROVED** [review]

**Review by stevepiercy — APPROVED** [review]
Thank you! Merging now.

**Comment by fredvd** [comment]
Thank you @ksuess for fixing the build error and others for reviewing. 

I created #1450 for continuation of the storybook build split from the main docs.

**Comment by stevepiercy** [comment]
This PR broke the build https://github.com/plone/documentation/actions/runs/4227241645/jobs/7341510254

**Pull request merged**
