### PR TITLE
a components chapter

### PR DESCRIPTION
**Pull request by jensens**

### CODE REVIEW

**Comment by stevepiercy** [comment]
@jensens this PR needs to be based against `6.0`, conflicts resolved, and moved out of Draft status. What do you need to push this forward? Please let me know. Thank you!

**Comment by jensens** [comment]
Well,  I forgot about this one ...
I  have no idea why I forgot about this chapter. 

What I need? Time. 
It seems conflicts are in the glossary:  it should be solvable.

It is unfinished. If nobody steps up to continue it, I will look at it when I have time to do so.

**Comment by stevepiercy** [comment]
Rebased to `6.0`, and resolved merge conflicts.

I'll trade you some of more free time for some of your knowledge. 😁

**Comment by stevepiercy** [comment]
@jensens we've started new guides in documentation, and this seems to be mostly a Conceptual guide. I'd like to move it there, then review this PR. What else needs to happen in this PR?

**Comment by jensens** [comment]
> @jensens we've started new guides in documentation, and this seems to be mostly a Conceptual guide. I'd like to move it there, then review this PR. What else needs to happen in this PR?

The last three sections need some content.

**Comment by stevepiercy** [comment]
@jensens maybe we break this PR into smaller chunks? It's OK if it's not perfect or complete. We can place TODOs in incomplete sections, and create issues so we remember to fill in the blanks. Also if we have sources from previous versions of the docs, we can at least link to them, and eventually port them to Plone 6. Sorry, I'm not a content expert, but I can at least organize and be a cheerleader.

**Comment by jensens** [comment]
@stevepiercy yes, this is fine.

**Comment by stevepiercy** [comment]
I've completed my revisions, added some todos, and created an issue at https://github.com/plone/documentation/issues/1775.

I'll merge as soon as it is green. Thank you, @jensens, this is a great start.

**Pull request merged**
