### PR TITLE
add MyST extensions

### LINKED ISSUE #1436: Update docs with videos and inline images
- add `html-image` and `sphinxcontrib.video` extensions to `conf.py`
- add `sphinxcontrib-video` in `requirements.txt`

_Originally posted by @MAX-786 in https://github.com/plone/volto/issues/4288#issuecomment-1418285998_

After this issue is complete, then append the new MyST and Sphinx extensions, and how to use them effectively, to the open pull request https://github.com/plone/documentation/pull/1404

### PR DESCRIPTION
**Pull request by MAX-786**
fixes #1436

### CODE REVIEW

**Review by stevepiercy — APPROVED** [review]

**Comment by stevepiercy** [comment]
Thank you! I'll update the git submodules, push, and let's see if it all builds.

**Comment by stevepiercy** [comment]
Looks good, except the style also needed to be brought over. I'll fix that now.

**Comment by stevepiercy** [comment]
It turns out that more work was necessary. I'm familiar with this issue, so I went ahead with the fix in https://github.com/plone/volto/pull/4376 and https://github.com/plone/documentation/pull/1438. Plone is unique with pulling in submodules in its documentation, and the fix is not obvious.

**Comment by MAX-786** [comment]
Thanks Steve 😊

**Pull request merged**
