### PR TITLE
Reading docs

### PR DESCRIPTION
**Pull request by svx**
Last missing bit for release! I want to make a release today !

### CODE REVIEW

**Comment by gforcada** [comment]
:+1: nice write up, could we merge all commits in a single one? So we get a better history for later on referring to them? :)

``git rebase -i master`` is your friend.

**Comment by svx** [comment]
I will keep that in mind for the next time, for now I just want to get the stuff build and published to docs.plone.org asap, since I am bit busy and I only have a short time window today :)

**Comment by gforcada** [comment]
Will you mind if I do the rebase then? :)

**Comment by svx** [comment]
@gforcada by all means go ahead, do it and merge ! I will start to write the changelog in the meantime !

**Comment by svx** [comment]
@gforcada ping I am a bit in a hurry here :)

**Comment by svx** [comment]
sorry no time as I said before, now building time .....

**Comment by gforcada** [comment]
sorry I was also busy, next time then

**Pull request merged**
