### PR TITLE
Improve caching caching: fix syntax, grammar, links

### PR DESCRIPTION
**Pull request by stevepiercy**

### CODE REVIEW

**Comment by svx** [comment]
Plese see: https://github.com/plone/documentation/issues/818

'd say stay as close to the norm as we can. We use Restructured text, so:
- double backticks means "inline literal". Normally rendered using monospace font, and it would be good for code commands. 
- single backticks are "interpreted text". They are domain- or application- specific, so we can define we want this to mean "Highlight" and/or "particular names". 

So I would re-phrase the example as:
```
After you updated `buildout.cfg` with your changes, you have to re-run buiildout again: ``/bin/buildout -v``
```

Now, of course how that "looks" is a question of CSS, but it does make sense in a semantic way.
So: 
- inline code use double backticks
- names of programs and things you want to highlight, could be rendered as bold with a yellow background or anyway else: use single backticks
- things with heavy emphasis, conventionally rendered in bold: use double asterisk

And again, please smaller pull requests, this will take now longer too review and so on ..

Thanks !

**Comment by stevepiercy** [comment]
> Plese see: #818

I didn't know it had been decided because the issue is still open. If it has been decided, then the style guide should be updated so there is something to use as reference.

I'll update this PR (and others) accordingly.

**Comment by stevepiercy** [comment]
> And again, please smaller pull requests

I broke them into one PR per page as requested. However, there is a problem with breaking these into even smaller PRs. Unless there is some other way I don't know about (suggestions very welcome!), GitHub requires that the developer create a new branch, commit the minor change, push to new branch, submit PR, all in order to have separate, "digestible" PRs. This is not insignificant overhead, not just from the mechanics, but more from the constant interruption of concentrating on writing docs. All this would impose a significant barrier to developers who want to make overhaul-scale updates. I would be strongly discouraged from making any contributions other than extremely minor changes. Other developers might feel the same way.

I don't know, maybe it's just my way of working that doesn't fit in with the Plone community. When I update docs, I read the whole thing from top to bottom, and make fixes as I go along. Is that weird?

**Comment by svx** [comment]
Here is how we usually work:

For *huge changes* like overhaul whole chapter we create branches in github.com/plone/documentation this enables other contributors to help/improve/fix.

Most of the **awesome** people who work on the docs, doing that even for every PR !

For *smaller* stuff like for example fixing grammar, typos and so on, we prefer one PR per file, better lots of small PR which we can review/merge faster than one big one.

This is proven to work for us very well !

**Comment by svx** [comment]
I will merge for now, but for the next time, please ask before you start so that we can discus/explain first !

Thanks !

**Pull request merged**
