### PR TITLE
small enhancements to WebDAV info

### PR DESCRIPTION
**Pull request by tkimnguyen**
based on an IRC chat with a new user trying to set up WebDAV. Needs some extra work re: how normal Plone users can be granted WebDAV access.

### CODE REVIEW

**Comment by svx** [comment]
Hi,

thanks would you mind to change certain things ? For example for 'Note', we do have ' ..note::' ins rst, which gives us as nicer layout. :), otherwise just leave it and I will change it in your branch later :)

**Comment by tkimnguyen** [comment]
I chopped out the WebDAV Notes section because it is generic WebDAV protocol implementation info and doesn't seem to belong in here.

**Comment by svx** [comment]
I will look at it tonight, there are still some .rst issues :)

**Comment by svx** [comment]
I have now an updated version, how I can get my changes into your pr ?

**Comment by svx** [comment]
@tkimnguyen I created a pr for your repo

**Comment by tkimnguyen** [comment]
Hi Sven - sorry I didn't see this until now - looking!

**Comment by tkimnguyen** [comment]
Merged

**Comment by svx** [comment]
Would you mind to send a pr for Plone 5 docs, too ?

**Comment by tkimnguyen** [comment]
Will do!

**Pull request merged**
