### PR TITLE
Continuous integration rewrite

### PR DESCRIPTION
**Pull request by gforcada**
This is my rewrite of the CI section.

I kept it short and a bit basic, without touching too many details, we could probably expand it more but as a first step probably is ok, and specially better than those rules that are no longer applying.

----
📚 Documentation preview 📚: https://plone6--1676.org.readthedocs.build/

### CODE REVIEW

**Comment by stevepiercy** [comment]
@gforcada I'm back from vacation. Please let me know if you would like some help with this PR. Thanks for your work on it!

**Comment by gforcada** [comment]
@stevepiercy hey, welcome back! I hope you enjoyed them!

Yes, it would be interesting to know how we can organize this document, and any follow up documents regarding CI.

This write up as it is, is a bit of a high level overview of the CI current status:

We use Jenkins and GitHub Actions thanks to PR-based development. `mr.roboto` provides the ink-link between GitHub and Jenkins.

We should split this into different sections/files probably though (following diataxis):

- a simple how-to guide to explain what you need to do to get your PR tested
- a tutorial/explanation on how the whole CI is orquestrated and managed
- not sure if we need a reference, maybe that would be more to document how `mr.roboto` is internally configured, etc ?

Would something like align with your ideas as well? 🤔 🍀

**Comment by stevepiercy** [comment]
@gforcada let's focus on the developer audience first. A how-to guide would be helpful. I think the pieces that we need more information include:

- Jenkins
  - What does it do?
  - How to run it through a GitHub comment.
  - How to run it through the Jenkins site.
  - How to diagnose a failure.
  - What to do when it fails.
  - How to retry a failed Jenkins run.
- `mr.roboto`
  - What does it do?
- [`@mister-roboto`](https://github.com/mister-roboto) for no PCA or email mismatch between PCA and GitHub. (I think the [current message](https://github.com/plone/volto/pull/6200#issuecomment-2252014953) only says there is no PCA, which confuses those people who have returned the PCA but their emails don't match, but that's a separate issue.)
- Other Plone core CI (Optional. Perhaps just a mention with links to relevant examples or repos, as each repo has its own implementation.)
  - Code format
  - Code lint
  - Tests
  - Documentation preview builds (WIP, see #1667)
  - Documentation link check
  - Documentation style and spell check
  - Build Docker images
  - Deployment
  - Other?

There are some places in the docs where some CI stuff is already mentioned, for example, [Change log entry](https://6.docs.plone.org/contributing/index.html#change-log-entry) and [Continuous integration](https://6.docs.plone.org/contributing/index.html#continuous-integration). Links between the content may be useful.

**Comment by gforcada** [comment]
@stevepiercy thanks for the write up, I will try to work on it piece by piece. Would it be worth creating small PRs so they can be easier to deal with?

**Comment by gforcada** [comment]
Here it is, it's maybe a first draft, I tried to keep it quick and simple so we can expand on it as feedback comes :)

Let me know if you want me to expand some sections, give more context, etc.

**Review by stevepiercy — APPROVED** [review]
@gforcada I did a review by editing your contribution as a foundation. Would you please review my changes, particularly for accuracy, and any other suggestions you might make? Thank you!

**Comment by stevepiercy** [comment]
The failing check is fixed in https://github.com/plone/documentation/pull/1693 and can be ignored. There are two other links that had temporary outages, but are working fine now.

**Comment by stevepiercy** [comment]
The failing CI check is a temporary outage of the Plone Community Forum, and can be ignored.

**Comment by gforcada** [comment]
@stevepiercy wow, so much better! 👑 thanks a lot!

I don't see any mistakes, so it should go in as you see fit 😄

**Comment by stevepiercy** [comment]
@gforcada thanks for push. Merging!

**Pull request merged**
