### PR TITLE
restructure: testing and debugging doc from deployment to dev, cachin…

### PR DESCRIPTION
**Pull request by thet**
…g to caching. Fixes: #468

### CODE REVIEW

**Comment by thet** [comment]
@polyester ready to merge!
IMO, this is a better structure. testing and debugging belongs to develop docs.

**Comment by thet** [comment]
@polyester @svx please review and please make a new release on docs.plone.org (with or without this pull request). then i can send out the Framework Teams "Call for PLIPs".
tnx!

**Comment by polyester** [comment]
I can make a release on docs.plone.org tonight.

**Comment by thet** [comment]
tnx!

**Pull request merged**
