### PR TITLE
nicer intro page for developers

### PR DESCRIPTION
**Pull request by polyester**
also fixes bug where paster/zopeskel info was not findable anymore

### CODE REVIEW

**Comment by svx** [comment]
Looks good, lets wait till travis is done before merge . Thanks !

**Comment by polyester** [comment]
btw: don't cherrypick to 5. I'm doing a different, but similar version for 5.0 branch, which includes upgrading info and leaves out ZopeSkel and stuff.

**Comment by svx** [comment]
Just one remark:

In develop/addons/index.rst you use a link to link to the docs part of dexterity

 (Dexterity is covered in detail in the `Dexterity Developer Manual <http://docs.plone.org/external/plone.app.dexterity/docs/>`_, which includes an extensive tutorial on
+setting up a Dexterity development environment.)

Would be a reference or a *document link* not more suited ? why use a *http link* ?

**Comment by polyester** [comment]
yep, I'll change that. Wasn't me... just copied from older version in dexterity.rst which I killed/integrated

**Comment by svx** [comment]
Well it is quite possible that I did that, when I was young and ...., anyway cool that we will get that fixed ! :)

**Pull request merged**
