### PR TITLE
Improve files download url section

### PR DESCRIPTION
**Pull request by jensens**
Improves: 

- information how to construct a download URL for any dx file field.

Changes proposed in this pull request:

- Explain what happens instead of only showing an opinionated example.

### CODE REVIEW

**Review by svx — APPROVED** [review]
As a note, personally I would not use ``in order`` we removed or changed that already on lots of locations.

But for now this is not the the style-guide :)

LGTM ! Thanks !

**Comment by svx** [comment]
Oh, yes circle ci is not working anymore, ignore if for now ! I will remove the test.
That is because of circle ci

**Comment by jensens** [comment]
Circle worked and found Javascript, I pushed it.

Well the chapter needs a complete overhaul anyway. It uses `plone.directives.form`, `implements` and other outdated. I'll open an issue, so it does not get lost.

**Comment by svx** [comment]
Yeah but we are using Circle 1 which will be retired in a couple of weeks anyway.
I will setup travis upcoming weekend !

**Pull request merged**
