### PR TITLE
Plone 5 upgrade guide tips

### PR DESCRIPTION
**Pull request by gforcada**
I basically wanted to write it down somewhere.

Should I create a subsection within the upgrade guide for this small changes?

### CODE REVIEW

**Comment by gforcada** [comment]
@svx @polyester any suggestion on the formatting? I would like to prettify this so it can be merged before it gets too outdated/I forgot what was all about.

btw if you don't mind I created a @plone/documentation-team so anyone can get the attention of the docs team without having to ping any individual alone, add all other team members though, I just added you two.

**Comment by svx** [comment]
Have a look at http://sphinx-doc.org/markup/para.html 

I use for this kind of stuff:
- .. note::
- .. warning::
- .. versionadded::
- .. versionchanged::
- .. deprecated::
- .. seealso

:)

**Comment by polyester** [comment]
I've done some quick-and-dirty formatting

**Comment by svx** [comment]
Yes, that is already a begin ! But besides the code we should also format the rest properly :)

For example in line 678 a ..note:: would make sense

**Comment by gforcada** [comment]
@plone/documentation-team I reformatted it a bit more and now it does not look so bad anymore. Probably the first section which are side effects of one PLIP it should be moved to the top once we have the proper LinguaPlone -> plone.app.multilingual docs as well.

**Comment by gforcada** [comment]
@plone/documentation-team anyone up to review and possibly merge? :-)

**Pull request merged**
