### PR TITLE
Fixed a small typo error

### LINKED ISSUE #1613: Small typo error in report an issue page
In the description of the new-issue-form, the word include has been written two times.
Screenshot 2024-01-23 225058

### PR DESCRIPTION
**Pull request by 07tAnYa**
Fixes #1613 

## Description

Made this statement: "Include include screenshots and any other helpful information." grammatically correct.

### CODE REVIEW

**Comment by stevepiercy** [comment]
@07tAnYa I would love to merge this pull request, but first please read and follow [Contributing to Plone](https://6.docs.plone.org/contributing/index.html). Once you have received the notification that you have been added to the Contributors Team, then please ping me here to remind me to merge this. Thank you!

**Review by stevepiercy — APPROVED** [review]
Awaiting Plone Contributor Agreement before merging.

**Comment by 07tAnYa** [comment]
I have signed the contributor's agreement on 11th Jan only, but till now I
haven't received the approval mail.

**Comment by stevepiercy** [comment]
@07tAnYa please see the last FAQ on https://plone.org/foundation/contributors-agreement:

> ### I signed the Agreement, but haven't been given access yet?
> Please allow a week for a response. Volunteers process the Contributor Agreements. If you have issues, such as making a spelling error in your email or GitHub username, please contact agreements@plone.org.

**Comment by 07tAnYa** [comment]
> @07tAnYa please see the last FAQ on https://plone.org/foundation/contributors-agreement:
> 
> > ### I signed the Agreement, but haven't been given access yet?
> > Please allow a week for a response. Volunteers process the Contributor Agreements. If you have issues, such as making a spelling error in your email or GitHub username, please contact [agreements@plone.org](mailto:agreements@plone.org).

Okay

**Comment by 07tAnYa** [comment]
> Awaiting Plone Contributor Agreement before merging.

@stevepiercy I have been assigned as a member of this community,

**Review by stevepiercy — APPROVED** [review]

**Comment by stevepiercy** [comment]
The failing test is due to two links as described in https://github.com/plone/documentation/issues/1612 and a third that recently added a redirect, which I will fix in another PR.

**Comment by 07tAnYa** [comment]
> The failing test is due to two links as described in #1612 and a third that recently added a redirect, which I will fix in another PR.

Am I able to fix that ? What are it's requirements?

**Comment by stevepiercy** [comment]
> > The failing test is due to two links as described in #1612 and a third that recently added a redirect, which I will fix in another PR.
> 
> Am I able to fix that ? What are it's requirements?

You can read the issue for details.

**Comment by 07tAnYa** [comment]
> > > The failing test is due to two links as described in #1612 and a third that recently added a redirect, which I will fix in another PR.
> > 
> > 
> > Am I able to fix that ? What are it's requirements?
> 
> You can read the issue for details.

Okay

**Pull request merged**
