### PR TITLE
Added warning for .zexp import/export

### PR DESCRIPTION
**Pull request by vedantc98**
Fixes: #972 

Improves:

- Introduction to content import/export for Plone sites.

Changes proposed in this pull request:

- Add a warning for .zexp method.

### CODE REVIEW

**Review by svx — CHANGES_REQUESTED** [review]
Please use valid *reST* here, meaning **Note** should be written as
```
.. note::
```

Further please follow the *one sentence** pre line rule. 
One line should be not longer than around 130 Chars.

**Comment by cewing** [comment]
@vedantc98 The docs are written in RestructuredText, or ReST.  As @svx notes, there are specific rules in ReST for making markup.  You can read [this basic primer](http://www.sphinx-doc.org/en/master/rest.html) for most of the rules you'd need.

As for the "one sentence per line" rule, that is a part of the style guide for this repository.  You can read about the style guide in the README file at the root of the repository.

**Comment by vedantc98** [comment]
Thanks @cewing and @svx .
I've updated my PR accordingly, hope this is good enough!

**Review by svx — APPROVED** [review]
Excellent ! Thanks !

**Pull request merged**
