### PR TITLE
Replace sphinxcontrib-spellcheck with Vale

### PR DESCRIPTION
**Pull request by stevepiercy**
Make it clear that the spellchecker is optional, to reduce a barrier to contributors.

### CODE REVIEW

**Review by fredvd — COMMENTED** [review]
Did you already test locally with Vale if that is easy to integrate for the docs? The issue is still that the enchant library is not optional, when I test the instructions by checking out the documentation repo in a clean dir and run `make html` I get the following error:

```
Documentation of plone.api initialized.
cd ./docs/ && /Users/fred/test/documentation/bin/sphinx-build -b html -d ../_build//doctrees   . ../_build//html
Running Sphinx v4.5.0

Extension error:
Could not import extension sphinxcontrib.spelling (exception: The 'enchant' C library was not found and maybe needs to be installed.
See  https://pyenchant.github.io/pyenchant/install.html
for details
)
make: *** [html] Error 2
```

**Comment by stevepiercy** [comment]
> Did you already test locally with Vale if that is easy to integrate for the docs?

See https://github.com/plone/documentation/issues/1347 which is a link in this PR. ;)

> The issue is still that the enchant library is not optional, when I test the instructions by checking out the documentation repo in a clean dir and run `make html` I get the following error:

Ah, that's right. I already have it installed, so I missed that. I should remove that step from the `Makefile` for now, too, in this PR. There are actually a bunch of other places where it needs to be removed, including volto. I will clean this up tomorrow. Thank you!

I think we are agreed, however, that the current spellcheck is broken and lacks a maintainer, and despite my request for guidance to fix it, I have received no response from the pyenchant maintainer. I have no hope of it getting fixed at this point.

**Comment by stevepiercy** [comment]
Instead of just ripping out `sphinxcontrib.spelling`, enchant, and pyenchant, I'm going to do a comprehensive replacement with Vale, either this or the next week.

**Comment by stevepiercy** [comment]
@ksuess @fredvd @polyester this is ready for review.

I kept the file `docs/spelling_wordlist.txt` because it has some good words that we should consider moving into our custom Vale dictionaries eventually, but not in this PR. We ought to leave something for newbies to do!

**Comment by stevepiercy** [comment]
I am not sure yet whether to install vale or use a [GitHub Action](https://github.com/errata-ai/vale-action). For the latter, I would have to change some settings.

For now I removed it from the `test` target in Makefile.

**Comment by ksuess** [comment]
> I am not sure yet whether to install vale or use a [GitHub Action](https://github.com/errata-ai/vale-action). For the latter, I would have to change some settings.

The GitHub Action seems to be maintained. So +1 from me because this means less to care for for us/you.

> 
> For now I removed it from the `test` target in Makefile.

**Comment by ksuess** [comment]
> I kept the file `docs/spelling_wordlist.txt` because it has some good words that we should consider moving into our custom Vale dictionaries eventually, but not in this PR. We ought to leave something for newbies to do!

yes, this can go reviewed in vocab/**/accept.txt

**Review by ksuess — APPROVED** [review]

**Comment by stevepiercy** [comment]
To use the GitHub Action, I would need to translate the command from Makefile to get the list of files to lint, and set an environment variable:

`VALEFILES       := $(shell find -L $(DOCS_DIR) -type d \( -path $(DOCS_DIR)/plone.restapi/lib/* -o  -path $(DOCS_DIR)"/plone.restapi/performance/*" \) -prune -false -o -type f -name "*.md" -print)`

How would I translate that to GitHub Actions? I have no idea.

It might be easier to just install Vale where all the other tests are run in CI and use `make vale`.

**Pull request merged**
