### PR TITLE
Remove duplicate contributing navigation

### LINKED ISSUE #1582: Contributing to projects has duplicate navigation
### Links of affected pages in Plone Documentation, if any.

- [Contributing to plone.api](https://6.docs.plone.org/plone.api/contribute/index.html)
- [Contributing to plone.restapi](https://6.docs.plone.org/plone.restapi/docs/source/contributing/index.html#)
- [Contributing to Volto](https://6.docs.plone.org/volto/contributing/index.html)

### Description

Visit any of the projects contributing pages. Observe that the navigation is duplicated. Links are valid in both copies, but the navigation items should not be duplicated.

Because each project maintains its own contributing policies in its documentation, we need to replace their toctree entries in `contributing/index.md` with entries to new pages in the subdirectory:

- `contributing/plone.api.md`
- `contributing/plone.restapi.md`
- `contributing/volto.md`

Each of these pages will have minimal content of just a heading with a reference link to the project's contributing documentation.

### PR DESCRIPTION
**Pull request by stevepiercy**
- Fixes #1582

### CODE REVIEW

**Comment by stevepiercy** [comment]
The failing workflow `Test` is due to a new version of Vale getting released. I have a temporary workaround in another PR by pinning it to 2.30.0, and created an [issue to fix it](https://github.com/plone/documentation/issues/1602), when someone has some time.

**Review by davisagli — DISMISSED** [review]
Possibly another use case for https://documatt.com/sphinx-reredirects/index.html (but I can't tell without trying whether it supports including the redirect pages in tables of contents)

But, LGTM as is too.

**Comment by stevepiercy** [comment]
We need to keep the milestone files in place to avoid Sphinx warnings, and when built they will get clobbered by sphinx-reredirects. This is OK. When I deleted the milestone files, Sphinx complained, for example:

```
/Users/stevepiercy/projects/Plone/documentation/docs/contributing/index.md:175: WARNING: toctree contains reference to nonexisting document 'contributing/plone-api'
```

We need the toctree entry, so we need the milestone files in source. Fixed in 1d80cc097884566431f140cd534359955bd0eaa5

**Review by davisagli — DISMISSED** [review]

**Comment by stevepiercy** [comment]
Requested in Discord of AI Team to add four 301 permanent redirects. Right now they return 200, then redirect, which is not great for SEO.

@polyester @fredvd

```nginx
rewrite ^/contributing/plone-api.html$ https://6.docs.plone.org/plone.api/contribute/index.html permanent;
rewrite ^/contributing/plone-restapi.html$ https://6.docs.plone.org/plone.restapi/docs/source/contributing/index.html permanent;
rewrite ^/contributing/volto.html$ https://6.docs.plone.org/volto/contributing/index.html permanent;
rewrite ^/install/install-from-packages.html$ https://6.docs.plone.org/install/create-project.html permanent;
```

**Comment by polyester** [comment]
done

**Pull request merged**
