### PR TITLE
Typos and headers

### PR DESCRIPTION
**Pull request by gforcada**
Fixed two typos:
- ' ot ' -> ' to '
- ' programmatically' -> 'programatically'

And fixed the headers as a bonus.

### CODE REVIEW

**Comment by svx** [comment]
thanks !

**Comment by fulv** [comment]
Actually, programmatically with two ms is the correct spelling.

**Comment by svx** [comment]
Fixed again, thanks !

Btw, I will open another ticket, this document needs review for Plone 5 there are Plone 3 and 4 notes in it, that should be checked and rewritten/updated, mentioning of Plone 3 could confuse people

**Comment by gforcada** [comment]
@fulv then my dictionary is wrong :-/

**Pull request merged**
