### PR TITLE
Fix broken links

### PR DESCRIPTION
**Pull request by stevepiercy**
----
📚 Documentation preview 📚: https://plone6--1743.org.readthedocs.build/

### CODE REVIEW

**Review by davisagli — CHANGES_REQUESTED** [review]
@stevepiercy I just changed this in https://github.com/plone/documentation/pull/1741 to fix a linkcheck error. Is it redirecting inconsistently?

**Comment by stevepiercy** [comment]
The advice in linkcheck was wrong, as it only detects the response from the server. I manually researched the new link based on the existing link.

- Original: https://formatjs.io/docs/getting-started/installation
- Current: https://formatjs.github.io/docs/getting-started/installation

It could be argued that the better link would be to the root of the site instead of how to install it. We actually need to improve this Glossary entry, now that I think about it. Update coming.

**Comment by davisagli** [comment]
@stevepiercy Oh I see, I used the new redirect but it didn't go to the same content as before. Mea culpa.

**Comment by stevepiercy** [comment]
@davisagli I think we're good now. One more review?

**Review by davisagli — APPROVED** [review]

**Pull request merged**
