### PR TITLE
added docker installation

### PR DESCRIPTION
**Pull request by Akshat2Jain**
I, Akshat Jain, agree to have this contribution published under Creative Commons 4.0 International License (CC BY 4.0), with attribution to the Plone Foundation.

### CODE REVIEW

**Comment by stevepiercy** [comment]
@Akshat2Jain FYI, if you intend to make more contributions outside of documentation, I would recommend that you sign and return the Plone Contributor Agreement, if you have not yet done so. For this repo, it is OK to include that statement of attribution.

**Review by stevepiercy — APPROVED** [review]
Thank you! I'll merge when the GitHub workflows pass.

**Comment by Akshat2Jain** [comment]
Thank You @stevepiercy.

**Comment by Akshat2Jain** [comment]
> @Akshat2Jain FYI, if you intend to make more contributions outside of documentation, I would recommend that you sign and return the Plone Contributor Agreement, if you have not yet done so. For this repo, it is OK to include that statement of attribution.

Hey @stevepiercy ,I have signed and sent a copy of my signature by email to the email listed in the agreement.

**Comment by stevepiercy** [comment]
@Akshat2Jain excellent! Please allow a few business days for a human to process and invite you to the Plone GitHub organization.

**Comment by ksuess** [comment]
Two installation methods are described in the documentation, with docker and without docker, but from packages. This PR is a change to the isntructions on installation from packages. So I think docker is no prequisite.

**Comment by Akshat2Jain** [comment]
> Two installation methods are described in the documentation, with docker and without docker, but from packages. This PR is a change to the isntructions on installation from packages. So I think docker is no prequisite.

Yes, you're right, but when performing sanity tests, docker is also checked, therefore I was getting an error for that because I hadn't installed docker.

**Comment by davisagli** [comment]
@ksuess Currently one of the final steps in cookiecutter-plone-starter is to run code formatters on the generated template. That is done using a docker image, so it fails if Docker is not installed and running.

**Pull request merged**
