### PR TITLE
Document LISTEN_PORT variable

### PR DESCRIPTION
**Pull request by Rudd-O**
Companion to https://github.com/plone/plone-backend/pull/69 .

### CODE REVIEW

**Review by stevepiercy — APPROVED** [review]
Let's also get @jensens review. Thank you!

**Review by jensens — APPROVED** [review]

**Comment by Rudd-O** [comment]
Yo I am not allowed to merge.  I can't merge this or the other PR.  @jensens @stevepiercy .

**Comment by stevepiercy** [comment]
> Yo I am not allowed to merge. I can't merge this or the other PR. @jensens @stevepiercy .

That is... strange. I see you as a Member of Plone, and the Author of the PR, and all the requirements are met for this protected branch. What do you see from your view?

I'll merge this PR, but first want to troubleshoot why you cannot merge your own approved PR here.

**Comment by Rudd-O** [comment]
image
if it helps

**Comment by stevepiercy** [comment]
@Rudd-O Thank you. It was my mistake. We actually limit merging of PR's to members of either [plone/documentation-team](https://github.com/orgs/plone/teams/documentation-team) or Organization and repository administrators. I assumed you were a member of the latter.

Merging.

**Comment by Rudd-O** [comment]
Thanks but the functionality PR is still not merged.  I can't push to plone/plone-backend so I can't reopen the PR from the repo itself.

**Pull request merged**
