### PR TITLE
update description

### PR DESCRIPTION
**Pull request by agitator**
Improves:
existing toolbar docs

### CODE REVIEW

**Comment by agitator** [comment]
@svx :doc: and :guilabel: look weird, how should that be formatted?

**Review by svx — COMMENTED** [review]
Should there be a . at the end ?

**Comment by svx** [comment]
@agitator what do you have against :doc: or :guilabel: ?

I mean it depends on the content :guilabel: is used for buttons, meaning that you do not write click on $foo but :guilabel:`$foo`.

But yeah I have to read the toolbat docs again, I am a bit in a hurry, I will check tomorrow :)

:doc: is used to directly link to a document -> http://www.sphinx-doc.org/en/stable/markup/inline.html

**Comment by agitator** [comment]
ping me on #plone tomorrow then ;-)

**Pull request merged**
