### PR TITLE
Add Products.CMFPlone is preferred location to identify Plone core pa…

### PR DESCRIPTION
**Pull request by stevepiercy**
…ckages

- See https://github.com/plone/Products.CMFPlone/issues/3594#issuecomment-2471860534

ping @petschki

----
📚 Documentation preview 📚: https://plone6--1776.org.readthedocs.build/

### CODE REVIEW

**Review by rohnsha0 — COMMENTED** [review]
I would suggest adding the text to `post in community` in the same point as `posting in CMFPlone repo`

**Comment by stevepiercy** [comment]
@rohnsha0 this renders as a paragraph, not a list. See the PR preview: https://plone6--1776.org.readthedocs.build/contributing/core/index.html#edit-packages.

Also the GitHub repo `CMFProducts.Plone` is primary, whereas the Community Forum is secondary. I could say post to both, but I think that in practice only those who have the institutional knowledge and will actually respond follow GitHub notifications on this repo, but not Community Forum. Maybe I'm wrong, but I've seen better response in `CMFProducts.Plone` than in Community Forum for these types of things.

**Comment by stevepiercy** [comment]
The failing linkchecks are transient and can be ignored.

**Comment by rohnsha0** [comment]
> @rohnsha0 this renders as a paragraph, not a list. See the PR preview: https://plone6--1776.org.readthedocs.build/contributing/core/index.html#edit-packages.
> 
> Also the GitHub repo `CMFProducts.Plone` is primary, whereas the Community Forum is secondary. I could say post to both, but I think that in practice only those who have the institutional knowledge and will actually respond follow GitHub notifications on this repo, but not Community Forum. Maybe I'm wrong, but I've seen better response in `CMFProducts.Plone` than in Community Forum for these types of things.

Ah! I somehow overlooked that... Sorry for that.. LGTM tho

**Review by rohnsha0 — APPROVED** [review]

**Pull request merged**
