### PR TITLE
WIP: Upgrade guide controlpanel

### PR DESCRIPTION
**Pull request by tisto**

### CODE REVIEW

**Comment by polyester** [comment]
yay Timo!

**Comment by tisto** [comment]
@ebrehault feel free to create your own branch or work on the 5.0 branch.

**Comment by polyester** [comment]
please: work an branches created FROM the 5.0 branch, and do not push directly on the  5.0 branch

**Comment by ebrehault** [comment]
@tisto @polyester ok done https://github.com/plone/documentation/pull/364

**Pull request merged**
