### PR TITLE
Fix: reST - a lot of it! I need a shower!

### PR DESCRIPTION
**Pull request by svx**
Fixes: reST

Improves: The Docs

Changes proposed in this pull request:

- fix headers

- fix notes and warnings

- remove
```
.. contents:: :local:
```
90% of it was not working anyway because of wrong syntax ...

### CODE REVIEW

**Comment by svx** [comment]
You can ignore the travis error this is because I forgot to pull before I created a branch

**Comment by polyester** [comment]
i can cherry-pick into 5.0 only this weekend, deadlines and meetings....

**Comment by svx** [comment]
@polyester Yes, please do it !

**Comment by svx** [comment]
@polyester 

I guess this will be a tricky one, this needs to be done with care, in lots of the changed files, there are adjustments for 5.1 only, if these changes will end up in 5.0 it will get confusing and messy for users.

Also there are new content which is not supposed to be in 5.0.

@esteele, @plone/release-team is there already a ETA for Plone 5.1. ?

:)

Going through the whole docs [this time 5.0] again and do all the changes from hand, takes a long time.

Personally I do not feel like spending hours again on this, only to see that a week or two later it is obsolete, because now 5.1 is released which has already all the changes in the docs.

:)

**Comment by gforcada** [comment]
@svx *(as part of the release team)*

the idea is to get another alpha/beta soonish:tm: but a final version is probably not going to happen overnight at least... by Sorrento? :-)

**Comment by polyester** [comment]
@svx cherry-picked into 5.0; in the process uncovered some damage done by an earlier pr to the 5.1 branch, fixed that with https://github.com/plone/documentation/pull/778

**Comment by svx** [comment]
@polyester I just checked and ... your cherry-picked lead exactly to what I wrote above, now we have lots of stuff which is for 5.1 and not for 5.0 in the docs of 5.0, for example:

https://raw.githubusercontent.com/plone/documentation/5.0/develop/addons/components/genericsetup.rst

```
.. versionadded:: 5.1

    When there is a profile with name ``default``, this is taken as the profile for installation.
    For more information on this plan,
    see `PLIP 1340 <https://github.com/plone/Products.CMFPlone/issues/1340>`_.

```


This is one of many things. If we do now a build it would be confusing for user, we talking about stuff which is not released, yet ! :)

Can you please revert your cherry-pick commit ?

Thanks ! :)

**Comment by svx** [comment]
@polyester I revert your commit, already :)

Which still brings us back to the beginning, how to proceed further ?

One other possible solution would be to revert the changes on the theme, create a temp. 5.1 branch of it and deploy all the nice improvements later when 5.1 will be released, and till then we stick with current version ...

Thoughts ? Ideas ?

**Comment by MrTango** [comment]
I thing it would be ok to have some parts in the docs for 5.1 as long as it's stated, that this is for Plone 5.1.
We already have Plone 5.1 alphas versions released, the question is here is it working there or only in the master or coming alphas?

**Comment by MrTango** [comment]
And what is the plan for rendering the docs?
Are we gonna have 5.1, 5.0 and 4.x or only 5.1 after it is released?

**Comment by svx** [comment]
@MrTango I just pushed a branch for the 5 branch with all these changes for 5 only.
This is better, the 5.1 branch has really too many changes and also please do not forget the audience :) It is not only for devs :) 

As far as for rendering, no, we will have one version for 5 on docs.plone.org, this is also, we changed a lot to make this possible and this is also one reason why I reverted the above commit.
The 5.0 branch will stay on GitHub.
With the docs for 5.1 you do not need a own docs build for 5.0 anymore.

**Comment by svx** [comment]
@MrTango To make it even more clear the when 5.1 is released, the docs will still the same:
http://docs.plone.org <- for 5 and 5.1

**Comment by svx** [comment]
@polyester https://github.com/plone/documentation/pull/779

**Comment by polyester** [comment]
I don't quite get it. My cherry-pick did not introduce this, https://github.com/plone/documentation/commit/57fbde5eef769c3da3b6542dccd7c335005f8251

A simple 'git blame' shows this change was introduced a year ago, by Maurits. 
https://github.com/plone/documentation/blame/5.0/develop/addons/components/genericsetup.rst

and I agree with @MrTango , there is something to be said for including upcoming stuff, as this was also in a section for add-on writers, who by definition are developers, and may want/need to know the 'upcoming' way to future-proof their writings.

As your original fix (and thus the cherry-pick) contains a lot of improvements, it would be better to revert the revert.

**Comment by svx** [comment]
No offense and with all respect, I disagree completely !

If you take the time and look carefully through all +140 files which got changed with my original PR, you will see that there are a lot really a lot of changes, which are for Plone 5.1.
This has nothing to do with the changes Maurits did.

We are not talking here about one or two sites where we have a

```
versionadded
```

There are a lot of other changes. If you new to Plone you will get confused, having suddenly on the docs stuff which is not working, or referring to not released versions, or telling you its removed  or other changes is confusing !

You will destroy any consistency through the docs, too.

 If you are a **experienced** developer, you know where to look for Plone 5.1 stuff if it is not on docs.plone.org, but please remember we have also new and/or less experienced developers!

Suddenly introducing these kind of stuff is IMHO bad, and I really do not get why,  I provided a PR #779 which is a fix for this for the time till 5.1 is released.

Also I am getting a bit worried, it took a lot of time and effort to improve this and for create this PRs. 
There are also carefully thought reasons behind it and there are reason why I already said in the begin of this discussion cherry-picking should be done in a carefully way.

To be honest suggesting reverting the revert, which I did with reasons ,explained, and provided a solution does not really motivates to put any effort/time anymore to the docs.

I am sorry but I am really offended by this !

**Comment by stevepiercy** [comment]
Sorry, I'm coming late to the Plone party. I maintain Pyramid and other Pylons Project docs, and I've felt soul-crushing despair while doing so, which was cured by some Labrador retriever therapy. 🐕 

Anyway, help me to understand the situation. I'm not clear how Plone release numbering aligns with Pyramid. I'll describe what we do in Pyramid first, and perhaps you can help me understand how you do things in Plone, and maybe you can use some of our practices to reconcile whatever problem arose in this issue.

Pyramid publishes and maintains two stable releases of documentation. Those are currently:

* http://docs.pylonsproject.org/projects/pyramid/en/1.7-branch/
* http://docs.pylonsproject.org/projects/pyramid/en/1.8-branch/

We configure Read the Docs to point the "latest" and "stable" versions as aliases to the latest and stable branch, currently 1.8.

* http://docs.pylonsproject.org/projects/pyramid/en/latest/
* http://docs.pylonsproject.org/projects/pyramid/en/stable/

We also maintain the bleeding edge branch in master:

* http://docs.pylonsproject.org/projects/pyramid/en/master/

We also have an archive of branches that are published and unmaintained, going all the way back to 1.0.

* http://docs.pylonsproject.org/projects/pyramid/en/1.0-branch/

Note that we have nice indicators for both older branches and bleeding edge branch.

HTH.

**Comment by polyester** [comment]
Sorry, not trying to offend; just trying to understand what is happening.
I am probably not the expert on git anyway, so I'm trying to see what happened, so I can learn.

I did spend 45 minutes doing that cherry-pick, looking over everything by hand, to make sure I would only do the right thing. But apparently not, although I still do not understand when I look at the changes in the actual cherry-pick (https://github.com/plone/documentation/commit/57fbde5eef769c3da3b6542dccd7c335005f8251) there seems nothing relating to 5.1. 

So, I will refrain, and conclude that I just don't understand what is going on, and not cherry-pick anymore until I understand what I'm doing.

**Comment by mauritsvanrees** [comment]
When I look at this pull request and Paul's cherry-pick, I see that both 'only' change header underlines and remove `.. contents:: :local:` and update a few notes or warnings to have an extra space or use lower case. I don't see anything in either of them that changes actual contents. So I don't see any inadvertent 5.1 changes that have gone into 5.0.  So both changes seem good to me.  Thank you both!

So if there is any code in the 5.0 branch which is not meant to be there, it is not caused by these changes.

Two of the `versionadded:: 5.1` were indeed done by me for GenericSetup/QI. See pull request #617 for discussion on whether that information should be there already in the 5.0 docs. Conclusion at the time was that it was good to have it, because someone who is creating a package for 5.0 may be very interested to see what he should or should not do to make it immediately compatible with 5.1.

If we are having seconds thoughts about this, I am happy to provide a pull request to cleanup `genericsetup.rst`.

**Pull request merged**
