### PR TITLE
Modified link to docker docs for persistent data and updated the Arbitrary user title

### PR DESCRIPTION
**Pull request by ichim-david**
----
📚 Documentation preview 📚: https://plone6--1679.org.readthedocs.build/

### CODE REVIEW

**Review by stevepiercy — COMMENTED** [review]
@ichim-david thanks for getting this started. I also added more to it. If my changes look OK, would you please merge this PR? Thank you!

**Review by stevepiercy — APPROVED** [review]
@ichim-david approving, as I don't know whether you can merge without an approval.

See https://github.com/plone/volto/issues/6157

**Comment by ichim-david** [comment]
@stevepiercy you will have to be the one to merge as I am not authorized to merge, I'm fine with the changes

**Comment by stevepiercy** [comment]
Does anyone happen to know who maintains https://www.dpg-physik.de/? [It keeps timing out in linkcheck](https://github.com/plone/documentation/actions/runs/9972689003/job/27556453960?pr=1679), but when I visit it, it is fine. @sneridagh or @tisto is this a KitConcept site?

**Pull request merged**
