### PR TITLE
Classic UI navigation Items sorted alphabetically

### PR DESCRIPTION
**Pull request by sitanshu05**
Changes have been made in the HTML is there any changes you would like me to make?

### CODE REVIEW

**Review by davisagli — CHANGES_REQUESTED** [review]
It looks like you did not add the correct files to the commit.

**Comment by sitanshu05** [comment]
> It looks like you did not add the correct files to the commit.


I have made changes in index.html after getting them from make html and make link commands could you please be more specific

**Comment by davisagli** [comment]
Look at https://github.com/plone/documentation/pull/1318/files which shows the changes included in this pull request. You have not submitted any changes to index.html, but you have included a bunch of Python wheels which is wrong.

**Comment by davisagli** [comment]
Actually index.html should not be checked in to the repository. It is generated from the Markdown files in https://github.com/plone/documentation/tree/6-dev/docs

**Comment by sitanshu05** [comment]
\ploneDocumentation\_build\html\classic-ui could you please confirm is this is the correct path 

could i also know how to pack the files as the changes I have made are reflecting locally 
image

**Comment by davisagli** [comment]
The process for building the docs locally is documented in https://6.dev-docs.plone.org/contributing/index.html and especially https://6.dev-docs.plone.org/contributing/setup-build.html

**Comment by sitanshu05** [comment]
When I try to commit the changes locally the index.html changes are not appearing and the only thing changing in the commit is python wheels how can i change this?

When i run git status no changes appear

**Comment by stevepiercy** [comment]
You should not commit `index.html`. The entire contents of the `_build` directory is ignored by `.gitignore`. We never want to commit anything in that directory.

Again, please review the full contributing documents as previously directed by both myself in https://github.com/plone/documentation/issues/1300#issuecomment-1247289154 and @davisagli in https://github.com/plone/documentation/pull/1318#issuecomment-1248488249.

I would like to help further, _after_ you do your part by following those directions. Thank you!

**Comment by stevepiercy** [comment]
Due to no further response, I am closing this PR. Please feel free to open a new PR, following our contributing guidelines.

**Pull request closed without merging**
