### PR TITLE
Improve upgrade guide to 5.1

### PR DESCRIPTION
**Pull request by mauritsvanrees**
Note: I started this change at the Plone conference 2018 in Barcelona.

Improves: the 5.1 specific upgrade guide

Changes proposed in this pull request:

- Add information per PLIP in the version specific upgrade guide for 5.0 to 5.1.

- Split that per PLIP into information for end users and for developers

While compiling this information, I have been wondering if some of this should be added to the add-ons upgrade guide instead. Or if the two should be merged together. Or if the end user part should be moved elsewhere. I thought that in earlier versions of the documentation we had this all in one place, not in two as now. I may misremember.

Suggestion: we could merge this PR first (if it is okay) so more documentation is there, and talk about correct placement afterwards in a new issue.

@thet For the HiDPI/Retina PLIP I have added two screenshots from you. See b13d2e607fe80d81cb7a3d79253bdf8f9f8da2d4. Is that okay?

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
@plone/framework-team I have described all PLIPs here, focusing on how this impacts end users and what developers should do to use the new features. Comments for improvement are welcome. Best is to view this file, which actually looks quite okay on github, including screen shots:
https://github.com/plone/documentation/blob/ploneconf2017-upgrade-guide-51/manage/upgrading/version_specific_migration/upgrade_to_51.rst

**Comment by svx** [comment]
@mauritsvanrees wow ! Thank you for this ! Thanks a lot !!!

Yeah, I am for merging and opening another ticket about separation/merging of docs parts !

If @thet is OK with it I will mege !

**Comment by gforcada** [comment]
Wow! That's just great!! Many many thanks :bow:

Once this is merged we (framework team) need to enforce that, at least, a section for each plip is created before closing as finished a plip.

**Comment by mauritsvanrees** [comment]
For the record, I copied some of this out of the add-ons upgrade guide, and some from a PyPI page, so some PLIP authors *did* write something at least.

**Comment by svx** [comment]
@thet I will merge now. If you do not agree with the usage of your images please let us know, so that we can work something out ! :)

Thanks !

**Pull request merged**
