### PR TITLE
Update basics.rst as default TinyMCE image is broken

### PR DESCRIPTION
**Pull request by sonawanemaitreya**
Fixes: #976 

Improves: broken image is replaced by proper screenshot

Changes proposed in this pull request:

-

-

-

### CODE REVIEW

**Comment by svx** [comment]
@sonawanemaitreya I reverted your merge, please do not just merge, please ask someone from the docs team to review first.
This is to make sure that all of us follow the best practices and style-guide.

We include pictures by robots or if that not possible by "hand" but then we place them into our docs and do not link to external sources.

If you have questions you always can open an issue on the docs issue tracker or ask on community.

Thanks !

**Comment by sonawanemaitreya** [comment]
My sincere apologies for the inconvenience. Its my early stages of contributing to open source so I didn't have proper idea for what was needed to be done. Of course now I understood what was my mistake.
Just one more question, cant contributors access image docs? Cause whenever I try to open this link - [https://docs.plone.org/_images](url) - it shows me "403 Forbidden" error.
Once again sorry for the nuisance caused.

**Comment by sonawanemaitreya** [comment]
Of course now you can download that image and place in docs there.

**Comment by stevepiercy** [comment]
@sonawanemaitreya as @svx mentioned, we have a guide for [Contributing To The Documentation](https://docs.plone.org/about/contributing/index.html) and a [Documentation Styleguide](https://docs.plone.org/about/contributing/documentation_styleguide.html).

Under **[General Guidelines](https://docs.plone.org/about/contributing/index.html#general-guidelines)**:

> 1. **DO NOT** commit to master directly. Even for the smallest and most trivial fix.
> 2. **ALWAYS** open a pull request and ask somebody else to merge your contribution.
> 3. **NEVER** merge it yourself.

I remember that I stumbled over the issue of adding images to the docs myself when I started out. We have something for _manually_ adding images in the [Documentation Styleguide](https://docs.plone.org/about/contributing/documentation_styleguide.html?highlight=images#documentation-structure), but I couldn't find anything about the automatic generation of screenshots via robots. How does a new contributor know when to add an image manually versus letting the robot take a screenshot automatically? There's an open issue #837 that mentions this. Sorry for the confusion.

**Pull request merged**
