### PR TITLE
make doormat mobile friendly

### PR DESCRIPTION
**Pull request by polyester**
Fixes: #

Improves: appearance of doormat, both on desktops and mobiles

Changes proposed in this pull request:

- give doormat-headings own class

- use more bootstrap pre-defined classes to space better

-

### CODE REVIEW

**Comment by gforcada** [comment]
@polyester any specific reason to switch plone.org links to http rather than keeping them on https?

**Comment by polyester** [comment]
Whoops no, copy paste error. I'll fix

**Comment by polyester** [comment]
should be fixed now. Sorry for multiple commits...

**Comment by svx** [comment]
@polyester can I merge or do you still working on it ?

**Comment by polyester** [comment]
I think I'm done. I've Title Cased All The Headings As Well.

**Comment by svx** [comment]
Ok .. merging !

**Comment by svx** [comment]
Done !

**Pull request merged**
