### PR TITLE
Update zopeskel references to bobtemplates.plone

### PR DESCRIPTION
**Pull request by gforcada**
Fixes: #

Improves:

Changes proposed in this pull request:
- Update link to docs.plone.org and reference bobtemplates.plone

### CODE REVIEW

**Comment by gforcada** [comment]
@jensens thanks for merging I manually cherry-picked it into 5.0

@plone/documentation-team what's the workflow for backporting to 5.0/4.3 branches? Just cherry-pick when something gets merged as I did?

**Comment by polyester** [comment]
@gforcada as far as I know, yes. 
It would be good to document this... that becomes kind of meta, but it does help. Maybe you can just press the 'up' arrow on your keyboard a few times and turn that into docs ;-)

**Comment by gforcada** [comment]
@polyester where do you want me to put that? :-)

**Comment by polyester** [comment]
@gforcada I would create a new file under /about/cherrypicking.rst 

and then we link to it from /about/contributing.rst (or not, as it's very specific). For now, leave the link, but an example how to cherry-pick would surely help others.

**Pull request merged**
