### PR TITLE
add viewlet docs

### PR DESCRIPTION
**Pull request by MrTango**

### CODE REVIEW

**Comment by MrTango** [comment]
could probably use some more rewriting, but so far better than having nothing in this section.

**Comment by petschki** [comment]
Regarding "moving a viewlet to a different viewletmanager" I'd recommend to mention this `zcml` snippet, placed in an integration package:

```xml
<configure xmlns="http://namespaces.zope.org/zope">

  ...

  <!-- move search viewlet to different viewletmanager -->
  <configure package="plone.app.layout.viewlets">
    <browser:viewlet
      name="plone.searchbox"
      manager="plone.app.layout.viewlet.interfaces.IPortalFooter"
      class="plone.app.layout.viewlets.common.SearchBoxViewlet"
      permission="zope2.View"
      />
  </configure>

  ...

</configure>
```

**Review by stevepiercy — DISMISSED** [review]
I reviewed and revised this document and pushed in ece9613d04598ec90e38f5fe1ef0763ccf88ac4e. This is great! Thank you!

**Comment by stevepiercy** [comment]
We can safely ignore the temporary 502 server error for https://52.demo.plone.org/en/ from linkcheckbroken. I notified the AI Team about it.

**Comment by stevepiercy** [comment]
I'm going ahead with a merge. Further revisions gladly accepted!

**Comment by MrTango** [comment]
> Regarding "moving a viewlet to a different viewletmanager" I'd recommend to mention this `zcml` snippet, placed in an integration package:
> 
> ```
> <configure xmlns="http://namespaces.zope.org/zope">
> 
>   ...
> 
>   
>   <configure package="plone.app.layout.viewlets">
>     <browser:viewlet
>       name="plone.searchbox"
>       manager="plone.app.layout.viewlet.interfaces.IPortalFooter"
>       class="plone.app.layout.viewlets.common.SearchBoxViewlet"
>       permission="zope2.View"
>       />
>   </configure>
> 
>   ...
> 
> </configure>
> ```

i added it to the viewlets docs in #1461

**Pull request merged**
