### PR TITLE
Dozens of reST fixes

### PR DESCRIPTION
**Pull request by stevepiercy**
Fixes many issues as recorded in #822.

Improves:
- fixes dozens of reST syntax errors, reducing the number of warnings to a mere 141.
- if the changed file also lacked an EOF or had tabs, I fixed that as well.

Changes proposed in this pull request:
- It would be good to resolve the remaining warnings for new contributors who are trying to make good, error-free contributions.

I was not sure what the author's intention was with the jumbled heading levels in `manage/installing/installation.rst`, so I made my best guess. Reviewers should look closely at this one in particular.

### CODE REVIEW

**Comment by svx** [comment]
This is the wrong branch:

https://community.plone.org/t/5-1-documentation-release-process-has-started/4049

Second, please do not create huge PRs, please cut them down.
For example one PR per chapter or even per file, this make is way easier to review, fix and merge faster.

**Comment by stevepiercy** [comment]
For a user who wants a 5.0.x version of the docs locally, this is the right branch.

I did not expect that this PR's size would be a problem.

**Comment by gforcada** [comment]
@stevepiercy I have to say that yes, *size matters*, reviewing a handful of line changes is ok, reviewing hundreds of changes, even if it's just syntax fixes (or specially because) can get your head spin easily.

More small pull requests are easier to handle, provide comments and refine further before merging, and as they are separate pull requests, ones can pass without problems while the harder ones are being processed.

That aside, thanks a lot for all your contributions! ❤️

**Comment by stevepiercy** [comment]
I appreciate that. I'll try to do better and make future PRs more digestible. I'm used to handling much larger PRs for Pyramid docs, so this one seemed small to me.

At this point, I'd have to redo the work and submit multiple PRs. I'm not motivated to do that. Sorry. Feel free to close this PR if you don't have time to review and merge it as is.

**Comment by gforcada** [comment]
I rebased the branch to 5.1 and reviewed it on https://github.com/plone/documentation/pull/830

**Comment by jensens** [comment]
FYI: #830 was merged, thanks @stevepiercy and @gforcada

**Pull request closed without merging**
