### PR TITLE
Add instructions for how to add a site to Netlify for preview builds …

### PR DESCRIPTION
**Pull request by stevepiercy**
…of documentation and storybooks

### CODE REVIEW

**Comment by stevepiercy** [comment]
We can safely ignore the failed link for https://52.demo.plone.org/. See https://community.plone.org/t/5-2-demo-is-down/18059

**Comment by tkimnguyen** [comment]
Seems good. Do you still need the todo at the top of the new material about whom to ping? You pretty much covered that in the new material.

**Comment by stevepiercy** [comment]
There is still a question about what the Admin actually does, for the benefit of their future self. I was hoping to capture that as well. Thus the requestor would know when they can complete their subsequent configuration steps.

**Comment by tkimnguyen** [comment]
Weren't you the one who told me that we didn't need to document everything here, especially if about some other software or system? 🤓 Netlify may change what they have us do

**Comment by stevepiercy** [comment]
Always being dogmatic serves no one well. There's always exceptions to guidance. In this case, we found that not documenting it wastes our time more than not, as this process and configuration is not obvious nor well-documented by Netlify, and it is performed so infrequently that we always forget what we did.

**Comment by tkimnguyen** [comment]
I wasn't the one who responded to the last Netlify add request so I'm not familiar with the steps required. Who responded in that case? Or would you like to submit a new one so I can go through it and document it?

**Comment by stevepiercy** [comment]
@fredvd or @polyester responded. If they want to add the missing piece, then that's up to them. If they don't respond in a week or so, then we can merge this as is, and their future selves will need to figure it out if we ever do this again. 😉 

I don't want to submit a new Netlify request.

**Comment by stevepiercy** [comment]
Will merge this when green.

**Comment by stevepiercy** [comment]
OK to merge. Temporary outage on linkcheck.

**Pull request merged**
