### PR TITLE
reduce nesting in the develop section

### PR DESCRIPTION
**Pull request by polyester**
Fixes: #580 #470

Improves: narrative explanation of the development sections

Changes proposed in this pull request:
- override the descriptions of external indexes in toc
- add some descriptive lines between sections
- fixed erroneous link to plone.app.contentlisting

### CODE REVIEW

**Comment by svx** [comment]
@polyester stupid question, but did you do a local test build and checked how it looks like ?

**Comment by polyester** [comment]
@svx yes I did. (screenshot only shows beginning)

developing for plone plone documentation v5 0 - mozilla firefox_008

**Comment by svx** [comment]
Nice thanks !

**Comment by gforcada** [comment]
thanks!

**Pull request merged**
