### PR TITLE
Polyester fixvarious

### PR DESCRIPTION
**Pull request by polyester**
sorry for the massive commit, I was on a roll a bit. Should dramatically reduce the number of build warnings and errors. Main ones left are 

- the bogus "image not readable' (they are fake because robotframework creates them)
- ones in /external (should be fixed by authors)
- and some in buildout.coredev section. Not fixing now because we should pull that in as external as well, I have some pull request there to make that better.

review carefully, there are some editorial decisions in here as well, such as dropping the docs for Linguaplone and raptus.multiplone, with a link to the old docs.

### CODE REVIEW

**Comment by svx** [comment]
@polyester I guess we also have to check which other tickets are may involved into this PR, I konw for example that we have a ticker for LingualPlone #323 .

So we should check the open tickets to and update or if possible close them.

The rest looks awesome thanks a lot !!

**Comment by polyester** [comment]
Don't merge yet, working on removing more linguaplone stuff (and yakshaving in the process)

**Comment by svx** [comment]
GO GO GO, just tell me when it is time for review/merge !

**Comment by polyester** [comment]
There's three mentions of LinguaPlone that I can't take care of, needs somebody with more knowledge. Documented in https://github.com/plone/documentation/issues/323

**Comment by polyester** [comment]
feel free to review/merge so far; the remaining ones need external review so that could be a while.

**Comment by svx** [comment]
In:

develop/plone/searching_and_indexing/indexing.rst

and
 
develop/plone/i18n/internationalisation.rst

we should fix the way how the links are done, currently they are using the 'list at the bottom style' like:

.. _zope.i18n: https://pypi.python.org/pypi/zope.i18n
.. _zope.i18nmessageid: https://pypi.python.org/pypi/zope.i18nmessageid

We should change that into 'in text links', because they are better/easier for translations.

@polyester what is your opinion, do that now, or some day later ?

**Comment by polyester** [comment]
done for these two. My opinion is about the same as fixing linebreaks: when opportunity arises. One day I will write a shell script to automagically do it. Today is not that day.

**Pull request merged**
