### PR TITLE
Update links to point to github

### PR DESCRIPTION
**Pull request by gforcada**
Changes proposed in this pull request:
- update links to point to github (rather than svn.zope.org)

It needs to be cherry-picked to 5.1 if accepted.

### CODE REVIEW

**Comment by gforcada** [comment]
@svx there a couple of links just after these ones that I changed that point to some gists made by you, should they be updated to somewhere else?

**Comment by svx** [comment]
Needs to go into 5.1 - DO NOT delete branch, till it is done

**Comment by svx** [comment]
@gforcada thanks ! 

Which gists do you mean ? :)

**Comment by gforcada** [comment]
@svx these ones (search on that rst):

```
* `See PlonePAS MemberDataTool <https://gist.github.com/svx/0f0b88ac2da4aaa38098>`_.

* `See PlonePAS MemberData class <https://gist.github.com/svx/7ced29e3dded6fe893c9>`_.
```

**Comment by gforcada** [comment]
@svx I manually cherry-picked the changes to 5.1, so I will remove the branch :-)

**Pull request merged**
