### PR TITLE
Use a custom robots.txt and set headers to block indexing on Netlify …

### LINKED ISSUE #1619: Netlify previews indexed by search engines. Should not, don't they?
### Links of affected pages in Plone Documentation, if any.

-

### Description

sorry, screenshot, as search results are local. You see what I mean…

grafik

### PR DESCRIPTION
**Pull request by stevepiercy**
…preview builds

Fixes #1619.

### CODE REVIEW

**Comment by stevepiercy** [comment]
Got it: https://deploy-preview-1620--6-docs-plone-org.netlify.app/robots.txt

**Comment by ksuess** [comment]
Even here in 'plone/documentation' I think the "branch deploy" option could be set to none. If I am correct, the Netlify deploy is not used for production deploy to docs.plone.org, but the _build dir of the rep is deployed to cloudflare as it is, isn't it?
grafik

**Comment by stevepiercy** [comment]
I think it always deploys at least the production branch, even if set to "None". There's a link to its docs for its settings below the options. That page is confusing.

**Comment by stevepiercy** [comment]
Also that screenshot is for Volto, not Documentation. I set both to None, but the production branch always gets deployed on Netlify. I don't know about Cloudflare.

**Comment by ksuess** [comment]
Yes, one published deploy always seems to be provided by Netlify. I also do not see a way to prevent every deploy but the preview, which is indeed where handy.
Approving.

**Review by ksuess — APPROVED** [review]

**Comment by davisagli** [comment]
@ksuess thanks!

**Pull request merged**
