### PR TITLE
Remove repeated reference to LDAP

### PR DESCRIPTION
**Pull request by techdev5521**
Thank you for your contribution to the Plone Documentation.

Before submitting this PR, please make sure:

- [x] You are following our [Documentation Styleguide](https://docs.plone.org/about/contributing/documentation_styleguide.html)
- [x] You are following our [General Writing Guidelines](https://docs.plone.org/about/contributing/rst-styleguide.html)

Fixes: 

Improves: **Documentation**

Changes proposed in this pull request:

- LDAP was referenced twice in the list of potential integrations and didn't need to be. Removing it makes the documentation easier to read.

### CODE REVIEW

**Review by stevepiercy — APPROVED** [review]

**Comment by stevepiercy** [comment]
Would you also please forward port this PR to branch `6`?

**Comment by techdev5521** [comment]
Sure, happy to! How do I do that?

**Comment by stevepiercy** [comment]
Same as you would submit any PR, but instead of using the default branch against which to make a PR, deliberately select the branch `6`. See https://github.com/plone/documentation/compare/6...5.2

**Comment by techdev5521** [comment]
It seems that the file I've proposed an edit to in the `5.2` branch doesn't exist in the `6` branch. Should I open a pull request to add this file to branch `6`?

**Comment by techdev5521** [comment]
I think I rebased the merge request successfully. Could you please confirm @stevepiercy ?

**Comment by stevepiercy** [comment]
@techdev5521 rebasing is not what you want. Your initial PR on the 5.2 branch was fine. I meant that after you merged the OK PR, then you would checkout the 6 branch, make the same change on 6, and create a second PR to the 6 branch. Sorry if I wasn't clear.

**Comment by stevepiercy** [comment]
As far as the missing file, the 6 branch has been reorganized a bit. You can find the same duplication here:
https://github.com/plone/documentation/blame/6/source/introduction.rst#L50

**Comment by techdev5521** [comment]
@stevepiercy making a separate pull request makes sense, I appreciate the help! It seems that I can't change this pull request back to branch `5.2` so I'll leave this closed and resubmit the same change for both branch `5.2` and `6`.

**Pull request closed without merging**
