### PR TITLE
just a typo in note about linebreaks

### PR DESCRIPTION
**Pull request by thet**

### CODE REVIEW

**Comment by svx** [comment]
Ah, good !

This was not spotted, because technical the word _at_ it is not a typo :) so much for automated testing :)

**Comment by thet** [comment]
nice, you have automatic spell checking?
yes, grammar errors cannot easily be checked automatically - yet.

**Comment by svx** [comment]
I am working on it, its almost finished

**Comment by svx** [comment]
'Only' thing to do now is to implement that into travis or any other CI

**Pull request merged**
