### PR TITLE
secureSend has been deprecated. To use send

### PR DESCRIPTION
**Pull request by terapyon**
Fixes: #

Improves:

Changes proposed in this pull request:
## 
## 
##

### CODE REVIEW

**Comment by svx** [comment]
@terapyon Thanks !

Can someone review ?

Please only merge if you cherry-pick it into the 5.1 branch too, if you do not want to do that, please do not merge at all, but add the label 'ready to merge.

Thanks !

**Comment by jensens** [comment]
change is fine.

**Comment by jensens** [comment]
So I need to improve my cherrypicking-skills.... I try to get this done, should be easy.

**Comment by jensens** [comment]
cherrypicking done - thats easy

**Pull request merged**
