### PR TITLE
Add a hint to reduce confusion about interface call vs. getAdapter.

### PR DESCRIPTION
**Pull request by jensens**

### CODE REVIEW

**Review by stevepiercy — APPROVED** [review]
On a roll, bay-beeeeeee! Thank you!

**Comment by jensens** [comment]
Ops, `hint` does not render? According to MyST doc it should. I should have checked better.

**Comment by stevepiercy** [comment]
Fixing now.

**Comment by stevepiercy** [comment]
See https://github.com/plone/documentation/pull/1419

**Pull request merged**
