### PR TITLE
Simplify the introductory container installation docs

### PR DESCRIPTION
**Pull request by stevepiercy**
Reopened against `6.0` branch.

See #1456 for discussion and background.

----
📚 Documentation preview 📚: https://plone6--1729.org.readthedocs.build/

### CODE REVIEW

**Comment by stevepiercy** [comment]
@davisagli what should we do with this old PR? Merge as is, amend, close?

**Comment by davisagli** [comment]
@stevepiercy This page and the "Examples of Plone 6 using containers" page should be replaced by a freshly written how-to guide (or several) about installing Plone using Docker / docker-compose / Docker Swarm. I can help with that, but I won't have time until after the conference.

The pages under "Official Images" are sort of a mix of how-to and reference and I don't have a clear idea what to do with them yet.

**Comment by stevepiercy** [comment]
@davisagli, here's what I have in mind. I think we're in agreement.

- [Containers](https://plone6--1729.org.readthedocs.build/install/containers/index.html) - Mix of Conceptual guide (introduction) and How-to (the rest of the page).
- [Official Images](https://plone6--1729.org.readthedocs.build/install/containers/images/index.html) - Each page is a mix of Reference (environment variables) and How-to, and should be split apart. I'd break each page into two.
- [Examples of Plone 6 using containers](https://plone6--1729.org.readthedocs.build/install/containers/examples/index.html) - How-to. Add orchestration examples using Docker / docker-compose / Docker Swarm (and maybe other tools?).

But all that is not relevant to the content in this PR, AFAICT. Is this content worth saving or deploying now? If not, let's close it and create a new issue that captures the plan instead.

**Comment by davisagli** [comment]
@stevepiercy We should merge this as is, now -- the commands that are updated were just plain wrong before these changes. Then I agree, we can work on the larger reorganization separately.

**Review by stevepiercy — COMMENTED** [review]
LGTM

**Pull request merged**
