### PR TITLE
Include CHANGELOG.md at the correct path, depending on context.

### PR DESCRIPTION
**Pull request by stevepiercy**
DO NOT MERGE until https://github.com/plone/volto/pull/3994 has been merged and https://github.com/plone/volto/issues/3992 has been resolved.

### CODE REVIEW

**Comment by stevepiercy** [comment]
This PR is now ready for review. @sneridagh @ksuess @tiberiuichim @davisagli

**Comment by davisagli** [comment]
@stevepiercy I don't see the release notes in the preview. Probably needs a submodule update. Or am I just looking in the wrong place?

**Comment by stevepiercy** [comment]
@davisagli thanks. Updated. Here is the preview: https://deploy-preview-1364--6-dev-docs-plone-org.netlify.app/volto/release-notes/index.html

The one question I have is whether to rename the page to be consistent with Plone Release Notes. For example: https://plone.org/download/releases/6.0.0rc1

**Review by davisagli — APPROVED** [review]
I would keep the "release notes" title, but also put changelog in the keywords for SEO

**Comment by stevepiercy** [comment]
OK, keeping the title of "Volto Release Notes" means:

1. Delete the title "Volto Release Notes" and its label above it from `release-notes/index.md`
2. Change the text in https://github.com/plone/volto/blob/master/CHANGELOG.md from "Change Log" to "Volto Release Notes". I would keep the file name as `CHANGELOG.md` because of the recent addition of towncrier and CI for it. I could also rename it and update towncrier and any other bits, but I'd rather not.

Before I commit that, I'd like at least confirmation from @davisagli and at least one more core contributor from Volto, just in case changing the text might affect how towncrier parses and writes to `CHANGELOG.md` or that the renaming is a Good Thing™.

**Comment by stevepiercy** [comment]
There we go! Much better: https://deploy-preview-1364--6-dev-docs-plone-org.netlify.app/volto/release-notes/index.html

**Pull request merged**
