### PR TITLE
document how to use Google Translate to translate content

### PR DESCRIPTION
**Pull request by erral**
Wait for https://github.com/plone/plone.app.multilingual/pull/462 and https://github.com/plone/plone.app.multilingual/pull/463 to be merged, they fix how this works in Plone 6.

----
📚 Documentation preview 📚: https://plone6--1723.org.readthedocs.build/

### CODE REVIEW

**Review by stevepiercy — APPROVED** [review]
This is awesome! Thank you! Will merge when green.

**Comment by erral** [comment]
Please, wait until the referenced PRs are merged. They fix the working of the translation system.

**Comment by stevepiercy** [comment]
@erral gotcha. I'll let you do the honors of merging.

**Comment by erral** [comment]
@stevepiercy I can't merge this. You can proceed because the referenced PRs are already merged.

**Comment by stevepiercy** [comment]
@erral that's odd. If you can write to the repo, creating a new branch and pushing commits, you should be able to merge the PR. I'll go ahead.

**Comment by erral** [comment]
> @erral that's odd. If you can write to the repo, creating a new branch and pushing commits, you should be able to merge the PR. I'll go ahead.

Yeah, it said that I wasn't authorized to merge the PR.

Is it perhaps because I created it?

**Comment by stevepiercy** [comment]
I don't think that would be it. It's OK for creators to merge their own PRs.

As a member of the Plone Developers Team, you have write access to this repo. Do you have two different logins for GitHub?

If it happens again, can you post a screenshot of what you see?

**Pull request merged**
