### PR TITLE
update buildout instructions to contribute to translations

### PR DESCRIPTION
**Pull request by vincentfretin**
Update again the buildout instructions to contribute to translations.

### CODE REVIEW

**Comment by vincentfretin** [comment]
@svx When are the Plone 5.2 html files regenerated?
I don't see my changes yet on
https://docs.plone.org/develop/plone/i18n/contribute_to_translations.html

**Comment by polyester** [comment]
@vincentfretin normally I deploy those;(has to be done by hand...) it's an extremely busy week for me, but should be there Friday.

**Comment by vincentfretin** [comment]
Thanks, no hurry. I just thought this was an automated process by now. :-) just wanted to be sure it will be updated at one point.

**Comment by polyester** [comment]
Done; now we know plonedoc also builds with Sphinx 3.11 and Python3.8 ;-)

**Pull request merged**
