### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by tkimnguyen**

### CODE REVIEW

**Review by stevepiercy — APPROVED** [review]
Additionally, should this be made against 5.2 and 6 branches? This is not very clear:
https://docs.plone.org/about/contributing/index.html#overview

**Comment by svx** [comment]
Hi 👋, 

5.2 yes! 6 is not needed since 6 is basically changing completely with every commit I make :) 
6 is currently super unstable since I am moving things around and changing everything. 
I will tell more about 6 soon! 

This is a signature

**Comment by tkimnguyen** [comment]
How should I make the same changes to the 5.2 branch? Manually?

**Comment by stevepiercy** [comment]
Here are a couple of ways:
- Do the same on 5.2 as you did for this PR.
- Checkout 5.2, create a new branch from 5.2, cherrypick this commit onto your branch, push your local branch to this remote, open new PR against 5.2 branch.

**Comment by tkimnguyen** [comment]
ok, done at https://github.com/plone/documentation/pull/1042

**Pull request merged**
