### PR TITLE
Fix for plone/cookiecutter-zope-instance 2.x: naming zcml variables

### PR DESCRIPTION
**Pull request by ksuess**
See https://github.com/plone/cookiecutter-zope-instance?tab=readme-ov-file#upgrading

Fix needed. Otherwise the build (`make build-backend`) fails.

### CODE REVIEW

**Review by stevepiercy — APPROVED** [review]
Thank you! Will merge right away.

**Comment by stevepiercy** [comment]
I'll fix the broken links in another PR.

**Comment by jensens** [comment]
No idea how its done best, but we need version-management for cookiecutters.
The call supports option `cookiecutter --checkout=1.0.1 ...`  for those who do not want the new 2.0.0 major release.

**Comment by stevepiercy** [comment]
@jensens are you talking about adding support for that call in the cookiecutter itself or in documentation, or both?

We could add a note to the documentation under [Install Plone 6](https://6.docs.plone.org/install/create-project.html#install-plone-6), but the assumption is that the user is creating a new project and should use the latest supported versions of everything. I think adding a note here would add confusion.

But in management of existing projects, we have a note to see the readme for [Configuration with `cookiecutter-zope-instance`](https://6.docs.plone.org/install/manage-add-ons-packages.html#configuration-with-cookiecutter-zope-instance). Would that be a good place to add a note about specifying the version of this cookiecutter?

Please let me know. Thank you!

**Comment by jensens** [comment]
We should change cookiecutter-plone-starter to pin it and update the Makefile snippet accordingly.

**Comment by davisagli** [comment]
@jensens I added an issue over there: https://github.com/collective/cookiecutter-plone-starter/issues/123

**Pull request merged**
