### PR TITLE
Update doormat.html

### PR DESCRIPTION
**Pull request by vivekptnk**
added proper formatting

Fixes: #Formatting

Improves: Readability

Changes proposed in this pull request:

-

-

-

### CODE REVIEW

**Comment by stevepiercy** [comment]
Hi @vivekptnk! GitHub indicates you are a first-time contributor to this repo. I don't know if mr.roboto that checks for your completed Plone agreement is configured for this repo or is not working, so I can't verify. Ping @svx and @polyester.

In case you have not completed the Contributor Agreement, please see https://plone.org/foundation/contributors-agreement

**Comment by vivekptnk** [comment]
I didn't sign the agreement I'll do it ASAP and update you with it.

**Review by stevepiercy — CHANGES_REQUESTED** [review]
These are only whitespace changes.

However @vivekptnk needs to sign the Contributor Agreement first, so do not merge yet.

**Comment by gforcada** [comment]
@stevepiercy documentation repository is whitelisted (i.e. not checked) if pull request authors have signed the contributors agreement. AFAIK it is not mandatory to do so in this repository.

**Comment by stevepiercy** [comment]
Thanks @gforcada. I remember several discussions I had at PloneConf in Boston over what is a "significant contribution" even in docs. I explicitly recall even the insertion of a comma could be considered a "significant contribution" and would therefore require a signed agreement. Perhaps that changed since then. Do we have a definitive answer to that matter for this repo?

**Comment by vivekptnk** [comment]
I have signed the agreement and sent it to the given mailing ID

**Pull request closed without merging**
