### PR TITLE
Addition to "Add a shortcut that brings the cursor to the search input field #1405 

### PR DESCRIPTION
**Pull request by ksuess**
Addition to #1405

### CODE REVIEW

**Comment by MAX-786** [comment]
@ksuess, this design gives the Search field a 'UNIQUE to Plone' design, so I can '+' vote for this design. I really appreciate your expertise and experience, and I have also been thinking about this design problem, and I just want to share my opinion and see if it might be worth considering as we continue to discuss the design:

1. Windows users who never used macOS sometimes take `⌘` for `Windows key` and IMHO I prefer changing indication to `^` from `⌘` according to the user's OS rather than hardcoding it (adding id='search-shortcut' to `<kbd>` will do ).
Screenshot_20230110_002733

2.  I think it would be a good UX if we have this 'shortcut hint' on the right since it would be more easily noticeable.
Screenshot_20230110_015645

Feedback welcome. Thanks 😊.

**Comment by ksuess** [comment]
>     1. Windows users who never used macOS sometimes take `⌘` for `Windows key` and IMHO I prefer changing indication to `^` from `⌘` according to the user's OS rather than hardcoding it (adding id='search-shortcut' to `<kbd>` will do ).
>        Screenshot_20230110_002733
> 
Yes, of course. You already prepared this distinction for OS.
I tried a short while to find a JINJA only solution for search.html and search_field.html. But it's not a low hanging fruit.

>     2. I think it would be a good UX if we have this 'shortcut hint' on the right since it would be more easily noticeable.
>        Screenshot_20230110_015645
> 
Yes, I am fine with the short cut on the right side. 
Reason for moving it to the left was the search page, where there is already a 'search' and 'reset' on the right side.
And then having the short cut on the same side for both: sidebar and search page.

--

A nice to have would be the elimination of the 'reset' by a little cross appearing for a filled search field. ;-)

Another nice to have would be to find a way that on ^k the search field is not glued to the top but with a small margin to the top.

**Comment by ksuess** [comment]
BTW 
grafik
is not unique to Plone but the kbd style throughout the documentation, either from Sphinx-book-theme or pydata-theme or Sphinx itself. @stevepiercy knows best.

**Comment by stevepiercy** [comment]
Before getting into the details of this implementation, I would like to discuss whether we should follow the search implementation of the grandparent theme, [`pydata-sphinx-theme`](https://pydata-sphinx-theme.readthedocs.io/en/stable/). I am more concerned about functionality—the features we implement—than their appearance at this point.

Advantages compared to this implementation:
- Modal is brought up with keyboard shortcut or clicking Search icon.
- No sidebar search input means no blank space in the sidebar on the Search results page.
- Clicking the search icon in the top navigation on the Search results page merely focuses the existing search input.

Disadvantages compared to this implementation:
- It is not clear that the Search input can be displayed with a keyboard shortcut until it is actually displayed.
- Even though the input is of `type="search"`, there is no delete icon to reset the input. I was unable to determine why this is so.
- The keyboard shortcut persists even when entering text. I would like it to go away so that the user does not attempt to use the keyboard shortcut to submit the search query.
- No submit button. It is not clear that the user can hit the `Enter` key to search, but maybe people just know that now?

**Comment by ksuess** [comment]
> Before getting into the details of this implementation, I would like to discuss whether we should follow the search implementation of the grandparent theme, [`pydata-sphinx-theme`](https://pydata-sphinx-theme.readthedocs.io/en/stable/). I am more concerned about functionality—the features we implement—than their appearance at this point.
> 
> Advantages compared to this implementation:
> 
>     * Modal is brought up with keyboard shortcut or clicking Search icon.
> 
>     * No sidebar search input means no blank space in the sidebar on the Search results page.
> 
>     * Clicking the search icon in the top navigation on the Search results page merely focuses the existing search input.
> 
> 
> Disadvantages compared to this implementation:
> 
>     * It is not clear that the Search input can be displayed with a keyboard shortcut until it is actually displayed.
> 
>     * Even though the input is of `type="search"`, there is no delete icon to reset the input. I was unable to determine why this is so.
> 
>     * The keyboard shortcut persists even when entering text. I would like it to go away so that the user does not attempt to use the keyboard shortcut to submit the search query.
> 
>     * No submit button. It is not clear that the user can hit the `Enter` key to search, but maybe people just know that now?

A modal would be in my opinion the next step. It would be the next step if the modal would include all features of the search form, especially the results. IMHO a search modal that leads to a classic search form instead of showing results (while typing) is not a plus to the current way of searching in Plone 6 documentation. Pydata theme does forward the user to a classic search page.
My current favorite for documentation search is the one of SvelteKit: https://kit.svelte.dev/
But the SveltKit search, even if someone would do the effort to implement it, is not 1:1 enough for Plone documentation, because the facet (filter by 'frontend', 'backend', etc) is in my eyes important. It is important as we will have a huge amount of pages / search results while the docu is growing to a size of the former Plone 5 documentation.

IMHO the search as it is now is OK and with the enhancement by the shortcut ^k it is even better.

What could be done for cleaning the situation of having two search fields while the search page is open:
Replace the search field in the left sidebar by a link to the search page.

**Comment by MAX-786** [comment]
> A nice to have would be the elimination of the 'reset' by a little cross appearing for a filled search field. ;-)

Yep, I was thinking the same :)

> Another nice to have would be to find a way that on ^k the search field is not glued to the top but with a small margin to the top.

I didn't quite understand ... looks fine to me.

> is not unique to Plone but the kbd style throughout the documentation, either from Sphinx-book-theme or pydata-theme or Sphinx itself. @stevepiercy knows best.

Oh got it,

**Comment by MAX-786** [comment]
> But the SveltKit search, even if someone would do the effort to implement it, is not 1:1 enough for Plone documentation, because the facet (filter by 'frontend', 'backend', etc) is in my eyes important. It is important as we will have a huge amount of pages / search results while the docu is growing to a size of the former Plone 5 documentation.
> 
> IMHO the search as it is now is OK and with the enhancement by the shortcut ^k it is even better.

@ksuess, yes IG for now we can go with this enhancement only, but in the future, if we are willing to implement Search Modal  we can go with the svelte 1:1 and I also have a solution to implement the facet, it may require a lot of work and attention 😖 but this is what I propose:

Instead of radio options to filter we can have a select option on the Search modal inside the search bar on the right side, and results can be shown just like svelte does.  

Screenshot_20230110_143241

As I said this requires a lot of work and may not be compatible with sphinx but it will modernize the Plone 6 docs if this can be done :).
@stevepiercy, love to hear your thoughts on this and this may overcome the disadvantages you stated. Thanks!

**Comment by stevepiercy** [comment]
Svelte's is nice, but I much prefer a page with full results instead of just 4 results. I like to open links in new tabs from the search results with adequate descriptions to give more context.

I mistakenly omitted from the Advantages that ours allows narrowing searches by topic/category.

Although I would like to discuss other search interfaces and results, for the sake of improving what we have now, I will defer that discussion to when we upgrade our theme to the latest from sphinx-book-theme (0.4.0rc1 is out now for testing). That will introduce a dark theme, which has its own design issues, including `kbd` styles that will affect search. Also we, and now the Plone Foundation, have been talking about using Nuclia for search on plone.org and docs: https://github.com/plone/documentation/issues/1184.

Back to my review of this PR, here are my suggestions.

Screen Shot 2023-01-10 at 2 08 39 AM

## `kbd` style

In a page where there is narrative text, the `kbd` style is fine as is, but in a search input where the font is much smaller than the body text, its `font-size` needs to be increased. The `⌘` is not legible. The vertical padding is too much. Here are suggested revised styles and a preview. Keep in mind that I do not have a Retina monitor for super crisp images, and I have a slight visual impairment (yay for aging!).

```css
.input-group-text kbd {
  padding: 0rem 0.4rem;
  font-size: 135%;
```

Screen Shot 2023-01-10 at 2 13 40 AM

## Search icon

I think the search icon (magnifying glass) is helpful and universally understand as "search". Google, DuckDuckGo, and many other search engines have this search icon in their search inputs. I would like to see it restored. In fact, I would prefer the icon instead of placeholder text to keep the design clean.

## Placeholder

I thought about this more, and I think it is better to have either just "Search", dropping "the docs", or nothing at all as the placeholder text. We should spell out words for the sake of both visually impaired users and translations, and "docs" should be avoided. Thus it becomes only "Search", but with the search icon reinstated, any placeholder text becomes unnecessary. Additionally it is clear that the search context is documentation, so we don't need to explicitly say "Search the docs", especially since it says "Plone Documentation v6.0" just above the sidebar search input.

## Search page

- Make the input a `type="search"`. This provides a clear or remove icon `×` that displays when the user starts typing in most browsers.
- Remove the `reset` button as redundant to the previous item.
- Replace the `search` text in the button with the search icon.
- Remove the placeholder text as redundant to the search icon.

Let's try to get consensus on this before moving forward. Thank you!

**Comment by ksuess** [comment]
From me a +100.

---
Placing the label on the right side as @MAX-786 suggested, is fine for me. I have no preferences anymore.

**Comment by MAX-786** [comment]
> Let's try to get consensus on this before moving forward. Thank you!

A "+" from me too :) (newbie question time: should I commit these suggestions or ksuess will do? and is it safe to close this PR #1405 now?)

> Also we, and now the Plone Foundation, have been talking about using Nuclia for search on plone.org and docs: https://github.com/plone/documentation/issues/1184.

After going through the PR, just wondering that does it have the potential to be a gsoc project? whether or not I would love to contribute to it, I may ask there directly for more info on this. :)

**Comment by stevepiercy** [comment]
> > Let's try to get consensus on this before moving forward. Thank you!
> 
> A "+" from me too :) (newbie question time: should I commit these suggestions or ksuess will do? and is it safe to close this PR #1405 now?)

I would say the easiest way forward would be to grab the bits and pieces that we like and merge and implement them into your PR for review.

> > Also we, and now the Plone Foundation, have been talking about using Nuclia for search on plone.org and docs: #1184.
> 
> After going through the PR, just wondering that does it have the potential to be a gsoc project? whether or not I would love to contribute to it, I may ask there directly for more info on this. :)

It might. I have no idea of the full scope. @ebrehault is one of the leaders of GSoC for Plone, and @polyester would have a good idea of what is necessary for search integration. I think he did something with Algolia search for previous versions of the docs. He ran into some trouble updating it, and we might just dump it for Nuclia.

**Comment by polyester** [comment]
Working on the Nuclia stuff, and have dropped the idea of making this into a GSOC project. Give it a few days.

**Comment by MAX-786** [comment]
> I would say the easiest way forward would be to grab the bits and pieces that we like and merge and implement them into your PR for review.

Sure! consider it done..... will be done by tomorrow (its 3am here so 😁😴)

> Working on the Nuclia stuff, and have dropped the idea of making this into a GSOC project. Give it a few days.

Oh looking forward to it 😁

**Comment by stevepiercy** [comment]
@ksuess can this PR be closed in favor of #1405?

**Comment by ksuess** [comment]
Suggestions are included in original PR https://github.com/plone/documentation/pull/1405

**Pull request closed without merging**
