### PR TITLE
Fix `collective.outputfilters.tinymceaccordion` configuration

### PR DESCRIPTION
**Pull request by stevepiercy**
This might need additional updates, but here's what I have so far.

----
📚 Documentation preview 📚: https://plone6--1794.org.readthedocs.build/

### CODE REVIEW

**Review by 1letter — CHANGES_REQUESTED** [review]
please use the pypi repro link, not the github repro link:
https://pypi.org/project/collective.outputfilters.tinymceaccordion/

**Comment by stevepiercy** [comment]
> please use the pypi repro link, not the github repro link: https://pypi.org/project/collective.outputfilters.tinymceaccordion/

Done in 20569b939b17c2e0e04196190a51670fd790bef2

**Comment by stevepiercy** [comment]
@1letter added your comment from https://github.com/collective/collective.outputfilters.tinymceaccordion/issues/13#issuecomment-2499969011 in 330fee32664ca40a215825b940675b32ce5b200f.

**Comment by stevepiercy** [comment]
Direct link to preview, after it finished building:

https://plone6--1794.org.readthedocs.build/backend/upgrading/version-specific-migration/upgrade-to-61.html#enable-the-tinymce-accordion-plugin

**Review by 1letter — CHANGES_REQUESTED** [review]
for simplification, do not version pinning. add the a addon to the egg section is the minimal requirement for a successfully buildout run. all other instructions are for people who know what to do

**Comment by stevepiercy** [comment]
Removed version pin in 5193a027db387c87d086a1ee8735889a6d54c7be.

**Comment by stevepiercy** [comment]
The simple buildout had a couple of issues.

1.  I moved installation of the add-on first, so that it would take care of any configuration.
2.  Site Setup > General > TinyMCE > Plugins and Toolbar had a tweaked out setting of `"items": "link media | template hr accordion"`. Could that be an issue with the installer? I corrected it to `"items": "link media | template hr | accordion"`.
3.  All other items were present, I assume because of running the add-on, but just in case the accordion was already installed from 6.0 and needed to be upgraded for 6.1, I modified the instructions to accommodate both a fresh install and a migrated install.

Please take a look as a final review.

**Review by 1letter — APPROVED** [review]

**Pull request merged**
