### PR TITLE
fix link to upgrade guide, tweak words, note P4

### PR DESCRIPTION
**Pull request by tkimnguyen**
Fixes: #739 

Improves: wording, clarifies this contains a lot of old P4 info

### CODE REVIEW

**Comment by svx** [comment]
Can that be merged ? I see the label '22 status: in progress' that is why I am asking.

**Comment by tkimnguyen** [comment]
@svx I think you can go ahead and merge. @jensens probably added that label because https://github.com/plone/documentation/issues/739 will require essentially a rewrite of this page. But for now merging this PR will let readers know the page may be out of date.

**Comment by jensens** [comment]
Well, I put this label on b/c there was no label on. Also the template was left emtpy, so I considered this WIP. I encourage you to label on your own, it is an excellent way to give more context on a PR.

**Comment by tkimnguyen** [comment]
ok I'll try to label from now on. in this case I've removed the in progress label :)

**Comment by gforcada** [comment]
@tkimnguyen @jensens @plone/documentation-team was that future-ported to 5.1 as well?

**Comment by tkimnguyen** [comment]
@gforcada I didn't do that myself. What's the best way to do that? Cherry pick these commits into that branch?

**Comment by gforcada** [comment]
@tkimnguyen yes that would be the easiest option

**Comment by tkimnguyen** [comment]
OK I think I did it: https://github.com/plone/documentation/commit/1435eaf5bf0acad065e9562e814b4a8255189838

**Pull request merged**
