### PR TITLE
document that when providing Volto translation one needs to run `yarn i18n`

### PR DESCRIPTION
**Pull request by erral**
These are the change we talked about last week. One needs to run `yarn i18n` in order to process those `po` files into `json` in order the CI checks to succeed and also Volto to load them properly.

----
📚 Documentation preview 📚: https://plone6--1691.org.readthedocs.build/

### CODE REVIEW

**Review by stevepiercy — APPROVED** [review]
I tested this out on a clean clone to ensure it worked, with my revision.

**Comment by stevepiercy** [comment]
Should we add a make command for `yarn i18n`, such as `make i18n`? We've been trying to unify all commands in the Makefiles.

Here's the output from the command.

```console
$ yarn i18n    
yarn run v1.22.19
$ pnpm --filter @plone/volto run i18n

> @plone/volto@18.0.0-alpha.42 i18n /Users/stevepiercy/projects/Plone/documentation/submodules/volto/packages/volto
> rm -rf build/messages && NODE_ENV=production i18n

Extracting messages from source files...
Synchronizing messages to pot file...
Synchronizing messages to po files...
Generating the language JSON files...
Merging @plone/volto-slate locales for de
Merging @plone/volto-slate locales for en
done!
✨  Done in 6.71s.

```

**Comment by stevepiercy** [comment]
The failing CI check can be ignored, as it is a temporary outage of the ZEO docs site.

**Review by ichim-david — APPROVED** [review]

**Comment by ichim-david** [comment]
@stevepiercy @wesleybl @davisagli @Tishasoumya-02 @JeffersonBledsoe I'm highjacking this pull request to let you know I'm on holiday until September so I won't review or check anything opensource or work related :).

**Comment by erral** [comment]
> Should we add a make command for `yarn i18n`, such as `make i18n`? We've been trying to unify all commands in the Makefiles.
> 

If such a work is being done, it makes total sense of course.

**Comment by stevepiercy** [comment]
Let's merge this now since it works. Later we can make an update in Volto's Makefile separately, then update the docs here. Thank you!

**Comment by stevepiercy** [comment]
I created a new issue in Volto, should we decide it would be good to do.

https://github.com/plone/volto/issues/6263

@erral I almost forgot, does this mean that we can now use Weblate for Volto translations? If so, then we can update this section, too.

https://6.docs.plone.org/i18n-l10n/contributing-translations.html#weblate-workflow

**Comment by erral** [comment]
> @erral I almost forgot, does this mean that we can now use Weblate for Volto translations? If so, then we can update this section, too.
> 

No, it is not ready yet.

**Pull request merged**
