### PR TITLE
Fixes #64

### LINKED ISSUE #64: Include to /documentation_styleguide_addons
http://plone.org/documentation/kb-old/how-to-create-a-sphinx-based-documentation-for-your-project

We should check what we should include from the old manual

Also we should explain better, what a README should include, like best practices

### PR DESCRIPTION
**Pull request by fulv**
@sneridagh, @bloodbare, please weigh in.

### CODE REVIEW

**Comment by fulv** [comment]
I meant, fixes plone/plonetheme.barceloneta#64

**Comment by svx** [comment]
@fulv @sneridagh @bloodbare 

Do you had time for looking at it ?

**Comment by fulv** [comment]
At this point I'm 99.9% sure that it can be merged.  Actually, the part
affected by this PR was added by @thetet.

**Comment by svx** [comment]
thanks !

**Comment by bloodbare** [comment]
Thanks @fulv !

**Pull request merged**
