### PR TITLE
Document portal action control panel

### PR DESCRIPTION
**Pull request by ebrehault**
Fixes: #

Improves: "Creating actions through-the-web" paragraph

Changes proposed in this pull request:
- update doc regarding the portal action control panel https://github.com/plone/Products.CMFPlone/issues/1342

Note: I have just updated the existing paragraph mentionning ZMI /portal_actions (located in /develop/plone/functionality/actions.rst), but maybe we should move that to /adapt-and-extend/config, don't you think?

### CODE REVIEW

**Comment by ebrehault** [comment]
By the way, it should not be merged until 5.1 is out.

**Comment by svx** [comment]
Yes, I will move it to /adapt-and-extend/config and will merge it as soon as 5.1 is out !

Currently we are busy to fix the latest loose issues and running test builds to release the docs for 5.0.3 on Monday or even earlier depending how fast we are and the internet connection at PLOG is

**Comment by svx** [comment]
@ebrehault we have now a branch for 5.1. To check one more time, can I move that to adapt-and-extend/config in the new 5.1 branch ?

**Comment by ebrehault** [comment]
@svx yes you can move it to 5.1

**Pull request closed without merging**
