### PR TITLE
Nuke trailing white space.

### PR DESCRIPTION
**Pull request by mauritsvanrees**
Same as #1229. See if a new PR is cleaner now, after deleting the Jenkins web hooks.

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
That did not help. It might be something with branch protection rules, but I did not see anything.

**Comment by stevepiercy** [comment]
Is it possible that there is something on the Plone GitHub organization settings that applies to all repositories? I do not have access to verify.

**Comment by stevepiercy** [comment]
Also I found nothing in GitHub Workflows in this repo that could trigger the Jenkins builds. Is there another repo that monitors this repo for any and all pull requests?

Where does `mr.roboto` actually live? Does it store configuration in an `.ini` file, environment variable, or database? Is it monitoring the GitHub Plone organization for changes?

**Comment by stevepiercy** [comment]
Does this ring a bell?

https://jenkins.plone.org/view/QA/job/qa-docs-age/

I don't have permission to configure Jenkins, only browse.

**Comment by mauritsvanrees** [comment]
> Is it possible that there is something on the Plone GitHub organization settings that applies to all repositories? I do not have access to verify.

I don't see anything like that.

> Also I found nothing in GitHub Workflows in this repo that could trigger the Jenkins builds. Is there another repo that monitors this repo for any and all pull requests?

`mr.roboto` does that. Or rather, on all or most plone repositories there are a few webhooks configured that send a notification to `jenkins.plone.org/roboto/various-service-urls`. Anything on `/roboto` is handled by `mr.roboto`, a service based on Pyramid.

> Where does mr.roboto actually live? Does it store configuration in an .ini file, environment variable, or database? Is it monitoring the GitHub Plone organization for changes?

The code is on GitHub, and here is the PR with the most important [things I changed today](https://github.com/plone/mr.roboto/pull/93).
Configuration is in several places: files on the server, files in the repo, and settings done manually in Jenkins.
It does not monitor, it only reacts to notifications/messages from GitHub, send via web hooks.

With the right permissions, you can see the logs. For an idea of what it does, here are the latest logs (newest is on top):

```
2022-04-07 20:03:40,670 INFO PR [plone/plone.staticresources#217](https://github.com/plone/plone.staticresources/pull/217): created pending status for plone 6.0 on python 3.9

2022-04-07 20:03:40,327 INFO PR [plone/plone.staticresources#217](https://github.com/plone/plone.staticresources/pull/217): created pending status for plone 6.0 on python 3.8

2022-04-07 20:03:39,951 INFO PR [plone/plone.staticresources#217](https://github.com/plone/plone.staticresources/pull/217): created pending status for plone 6.0 on python 3.7

2022-04-07 20:03:38,434 INFO PR [plone/plone.staticresources#217](https://github.com/plone/plone.staticresources/pull/217): changelog entry: success

2022-04-07 20:03:36,104 INFO PR [plone/plone.staticresources#217](https://github.com/plone/plone.staticresources/pull/217): Contributors Agreement report: success

2022-04-07 20:03:34,768 INFO Commit: not in sources - plone/plone.staticresources - images-in-search do nothing

2022-04-07 20:03:33,932 INFO PR [plone/plone.staticresources#217](https://github.com/plone/plone.staticresources/pull/217): with action synchronize

2022-04-07 20:03:33,624 INFO Commit: send mail: coredev push to plone.staticresources

2022-04-07 20:03:33,624 INFO Commit: on plone/plone.staticresources images-in-search [ae58106d5bacfe2c4a0c4f6bb9977a497caabae1](https://github.com/plone/plone.staticresources/commit/ae58106d5bacfe2c4a0c4f6bb9977a497caabae1)

2022-04-07 20:02:29,746 INFO PR [plone/plone.staticresources#217](https://github.com/plone/plone.staticresources/pull/217): created pending status for plone 6.0 on python 3.9

2022-04-07 20:02:29,393 INFO PR [plone/plone.staticresources#217](https://github.com/plone/plone.staticresources/pull/217): created pending status for plone 6.0 on python 3.8

2022-04-07 20:02:29,055 INFO PR [plone/plone.staticresources#217](https://github.com/plone/plone.staticresources/pull/217): created pending status for plone 6.0 on python 3.7

2022-04-07 20:02:27,618 INFO PR [plone/plone.staticresources#217](https://github.com/plone/plone.staticresources/pull/217): changelog entry: error

2022-04-07 20:02:25,514 INFO COMMENT [plone/plone.staticresources#217-1092045753](https://github.com/plone/plone.staticresources/pull/217#issuecomment-1092045753): IGNORED as it is from mister-roboto

2022-04-07 20:02:23,409 INFO PR [plone/plone.staticresources#217](https://github.com/plone/plone.staticresources/pull/217): Contributors Agreement report: success

2022-04-07 20:02:21,115 INFO PR [plone/plone.staticresources#217](https://github.com/plone/plone.staticresources/pull/217): with action opened

2022-04-07 20:02:10,851 INFO Commit: not in sources - plone/plone.staticresources - images-in-search do nothing

2022-04-07 20:02:04,109 INFO Commit: send mail: coredev push to plone.staticresources

2022-04-07 20:02:04,108 INFO Commit: on plone/plone.staticresources images-in-search [b6a5bee46b55f287ed9074e7e52d8849d1456bc8](https://github.com/plone/plone.staticresources/commit/b6a5bee46b55f287ed9074e7e52d8849d1456bc8)

2022-04-07 20:02:03,127 INFO Commit: on plone/plone.staticresources images-in-search [a2b74645dc74530cb0320c194feb011054b73a82](https://github.com/plone/plone.staticresources/commit/a2b74645dc74530cb0320c194feb011054b73a82)

2022-04-07 20:02:02,893 INFO Commit: on plone/plone.staticresources images-in-search [3bbe2efb62bd4ed92a4525cc8d9eb997754e570d](https://github.com/plone/plone.staticresources/commit/3bbe2efb62bd4ed92a4525cc8d9eb997754e570d)

2022-04-07 19:53:27,676 INFO PR [plone/Products.CMFPlone#3488](https://github.com/plone/Products.CMFPlone/pull/3488): created pending status for plone 6.0 on python 3.9

2022-04-07 19:53:27,220 INFO PR [plone/Products.CMFPlone#3488](https://github.com/plone/Products.CMFPlone/pull/3488): created pending status for plone 6.0 on python 3.8

2022-04-07 19:53:26,864 INFO PR [plone/Products.CMFPlone#3488](https://github.com/plone/Products.CMFPlone/pull/3488): created pending status for plone 6.0 on python 3.7

2022-04-07 19:53:25,401 INFO PR [plone/Products.CMFPlone#3488](https://github.com/plone/Products.CMFPlone/pull/3488): changelog entry: error

2022-04-07 19:53:23,496 INFO PR [plone/Products.CMFPlone#3488](https://github.com/plone/Products.CMFPlone/pull/3488): Contributors Agreement report: success

2022-04-07 19:53:21,722 INFO Commit: not in sources - plone/Products.CMFPlone - move-plone-base-2 do nothing

2022-04-07 19:53:21,256 INFO PR [plone/Products.CMFPlone#3488](https://github.com/plone/Products.CMFPlone/pull/3488): with action synchronize

2022-04-07 19:53:20,603 INFO Commit: send mail: coredev push to Products.CMFPlone

2022-04-07 19:53:20,602 INFO Commit: on plone/Products.CMFPlone move-plone-base-2 [2e8b3cc1521709fec4d16b2ee5bcd5091fdc577a](https://github.com/plone/Products.CMFPlone/commit/2e8b3cc1521709fec4d16b2ee5bcd5091fdc577a)
```

**Comment by mauritsvanrees** [comment]
@gforcada Do you know what is responsible for still adding the Plone Jenkins CI pending checks on a PR?
I have disabled it in `mr.roboto` code for this repository, and Fred has deployed it, and the logs suggest that this worked. I have even first deactivated the Jenkins web hooks from this repo and when that did not work I deleted them. But even with a new PR, these checks are still added.
I suspected branch protection settings, but don't see it.

**Comment by stevepiercy** [comment]
I removed the remaining three webhooks. One was for Gitter (which was replaced by Discord), and the other two were for hosts that no longer exist and their payloads had not been received in years.

Is it possible that a GitHub user exists which watches this repo for PRs?

Is it possible that another automatic process indirectly triggers Jenkins? Although unlikely, I wonder if something "clever" was set up, like an IFTTT workflow or a GitHub App?

This issue a smell of a GitHub Organization level configuration item. I've combed over the repo settings three times now. Could an org level user please take another look at the following? (URLs based on Pylons org GitHub URLs, replacing the org user with `plone`):

- https://github.com/organizations/plone/settings/hooks
- https://github.com/organizations/plone/settings/oauth_application_policy
- https://github.com/organizations/plone/settings/installations
- https://github.com/organizations/plone/settings/applications
- https://github.com/organizations/plone/settings/apps

**Comment by mauritsvanrees** [comment]
> * https://github.com/organizations/plone/settings/hooks

I deactivated a failing hook that tried to send info to Slack.
There is a working one left which sends commit info to gitter.im, which can probably be deactivated as well.

> * https://github.com/organizations/plone/settings/oauth_application_policy

Only one is this list: https://workingcopy.app, some Mac Git app.

> * https://github.com/organizations/plone/settings/installations

See screen shot:

Screenshot 2022-04-11 at 10 05 00

I have approved the pending Netlify requests, but these seemed to have been old ones that were really already approved, for `documentation` and `volto`.

Cypress and Travis CI are the only ones with access to all repos. The others do not have access to the documentation repo, except of course Netlify.

> * https://github.com/organizations/plone/settings/applications

Screenshot 2022-04-11 at 10 10 33

mr.roboto and Jenkins are in there, but I did not see anything in the settings that looks like it would be generating new checks here.

> * https://github.com/organizations/plone/settings/apps

Nothing in here.

**Comment by stevepiercy** [comment]
Thanks for checking, @mauritsvanrees. It's a mystery.

**Comment by gforcada** [comment]
@mauritsvanrees 🤔 with your changes deployed and specially the hooks removed, I'm not sure how is actually mr.roboto notified at all 😕 that should be the only source mr.roboto is using to act, so if no hooks, it should not know anything about the repo activity... looks interesting to debug what's going on here ;)

**Comment by mauritsvanrees** [comment]
Let me try it once more in (again) a new PR.

**Comment by mauritsvanrees** [comment]
Nope, PR #1231 immediately adds the pending Jenkins tests. There are no hooks. Nothing comes in the roboto log. I give up.

**Comment by stevepiercy** [comment]
Thank you for trying.

**Comment by gforcada** [comment]
@mauritsvanrees I do see that on your #1231 on the commit there there are jenkins CI jobs pending... I created another PR, just for testing #1232 , and so far, this one is not having the jenkins CI jobs 🤷🏾 they both are meant to be merged on `6-dev` 🤔

**Comment by mauritsvanrees** [comment]
Aha. I used the same test branch for my PRs. Maybe GitHub somehow remembers the checks then?
Seems strange. But if they are now gone for a really new PR, then that is great! Thanks for checking.

**Comment by stevepiercy** [comment]
Ah, I didn't notice that it was the same branch. TIL. Thank you both for resolving this annoyance.

**Pull request closed without merging**
