### PR TITLE
classicui: copy "Working with Content" from 5.2-myst

### PR DESCRIPTION
**Pull request by jensens**

### CODE REVIEW

**Comment by jensens** [comment]
robodoc robotshots are missing here. This is challenging. Parts of the puzzle:

The robot files are here https://github.com/plone/Products.CMFPlone/tree/master/Products/CMFPlone/tests/robot/robodoc

For Plone 5, then they are generated by mr.roboto/Jenkins here https://github.com/plone/documentation-roboshots
And somehow transferred to this repo on build time. 

To much magic.

**Comment by jensens** [comment]
For now I copied over the missing files.

**Comment by stevepiercy** [comment]
Please do not do all the files at once. This is why Plone 5.2 docs have so many errors, copy-pasta from previous generations.

Each file must be reviewed and curated for accuracy. There is no way that this will ever get reviewed by me (or anyone with hundreds of hours of free volunteer time). We need to break it into baby steps so that we can get something done. Thank you!

**Comment by jensens** [comment]
Yay, so it wont happen. 

The whole chapter is good as is and better than nothing. Probably it was the best part the old documentation we had. 

I neither have the time nor the energy to break this down into pieces. In this case I close this and delete the branch. 

But I don't think we can afford to do that. We need basic end user docs for classicui. 

I would look into getting fresh screenshots in (and @thet already said he would to take a look too) and review the content as-is. Not more, not less. Perfect is the enemy of good.

**Comment by stevepiercy** [comment]
> Yay, so it wont happen.

Correct, as far as it will not happen in the way that you would like. Sorry. It will happen in a manner that allows thoughtful review. 

> The whole chapter is good as is and better than nothing.

It shall always exist in Plone 5.2 docs. That is not going away.

> I would look into getting fresh screenshots in (and @thet already said he would to take a look too) and review the content as-is.

We are talking about how to automate screenshots for Volto and Classic UI. @datakurre recently made some suggestions in Discord in the #documentation channel. Options include Cypress, Playwright, and others. We could use someone skilled with automation to figure out how to take a screenshot and commit it to a repository whenever there is a change in docs files.

>  Perfect is the enemy of good.

Yup, and its corollary, "Rushed is the enemy of good." You may have also heard, "Good, quick, and cheap: pick two." We've already picked cheap through volunteer labor.

The second biggest issue with this PR, after its mammoth size, is that the Markdown files are placed in `_static`. That ignores the plan that the Documentation Team has laid out for integrating Classic UI docs.

I suggest that you discuss your plans amongst the Documentation Team before blazing a new path. I'm sure there is some way to do all this without alienating anyone. Thank you!

**Comment by polyester** [comment]
For reference: the 'roboshots' stopped working for the 5.2 branch a long time ago, that setup was extremely fragile, needing a whole slew of tools with intricate version-number dependencies. And even when it worked, it required slaughtering various cute furry animals at full moon while throwing salt over your left shoulder _(for anybody not named "Asko")_...  
By now they are just a bunch of hand-made screenshots.

**Comment by datakurre** [comment]
@polyester Thanks! I tried bring up all the issues with robots, but thought that you found a more robust way with Puppeteer. But maybe that was just an idea. 🙈 No free lunches here :(

**Pull request closed without merging**
