### PR TITLE
upgrade doc regarding plone app users

### PR DESCRIPTION
**Pull request by ebrehault**

### CODE REVIEW

**Comment by ebrehault** [comment]
bad branch, sorry

**Comment by tisto** [comment]
@polyester @svx it seems I'm not the only one who makes this mistake. :) 

Can't we make the current Plone version the master branch? Or at least make the 5.0 branch the default one? It is really confusing that the default master branch is not used at all.

**Comment by polyester** [comment]
that was going to be my job in Munich ;-)

Yes, we need to cut a 4.x branch from master, and then make 5.0 the default branch. And do the same on github.com/plone/papyrus, and reflect it in their respective readme's. So it's a bit of a shuffle, which I can't do before friday morning.

**Comment by tisto** [comment]
Ok, cool. Thanks for working on this! :)

**Pull request closed without merging**
