### PR TITLE
Fixes - 'make html' outputs wrong build dir to find the generated documentation

### LINKED ISSUE #1477: 'make html' outputs wrong build dir to find the generated documentation
### Plone Documentation versions affected

- [ ] 5.x
- [X] 6.x

### Description

At the end of running `make html` in the documentation repository root, the Makefile prints:

" Build finished. The HTML pages are in ../_build//html. "

But the builded docs are in in  "_build/html"

### PR DESCRIPTION
**Pull request by AdarshRawat1**
Closes #1477

I, Adarsh Rawat, agree to have this contribution published under Creative Commons 4.0 International License (CC BY 4.0), with attribution to the Plone Foundation.

### CODE REVIEW

**Comment by stevepiercy** [comment]
Hm. The `test` job did not run. I will try to get it to run by closing and reopening this PR. It could have been related to the GitHub incident: https://www.githubstatus.com/history

**Comment by stevepiercy** [comment]
I'm going to try this again. I think this is a permissions issue. Please stand by.

I have just now added Contributors to this repo with Triage access. Let's see if that has any effect.

**Comment by stevepiercy** [comment]
Nope. Bumping access to Write permission for Contributors now.

**Comment by stevepiercy** [comment]
Dropping access back to Read for Contributors. I think I need to make updates to allow external branches to run, similar to what @davisagli did for `volto`. Will do that next.

**Comment by stevepiercy** [comment]
Yup, that was it. Thanks @davisagli for the code.

**Review by stevepiercy — APPROVED** [review]
Thank you!

**Comment by AdarshRawat1** [comment]
Thank you @stevepiercy @stevepiercy

**Pull request merged**
