### PR TITLE
Fix broken link and improve language

### PR DESCRIPTION
**Pull request by staeff**
Fixes: 
- broken link for 'Using BTrees example'
  Improves:
- Language

### CODE REVIEW

**Comment by polyester** [comment]
both CI checks failed due to a non-related issue (basically, plone.app.iterate got version-bumped, and I need to adapt the robot-screenshots. That led to much bike-shedding and yak-shaving, as FIrefox is wonked, won't be able to finish until friday or saturday). But just to state the failures are not related to this PR)

**Comment by svx** [comment]
@polyester What is the status here, do robot-screenshots still needs to be adapted ?

**Comment by polyester** [comment]
no, robot-screenshots have been fixed.

**Comment by svx** [comment]
OK, so meaning we can ignore travis [complaining about bootstrap] and merge ?

**Comment by polyester** [comment]
Caught one more typo. It's a lot better than it was, so yes merge and cherry-pick to 5.0

**Pull request merged**
