### PR TITLE
Add wheel to requirements

### PR DESCRIPTION
**Pull request by stevepiercy**
See #1395

### CODE REVIEW

**Review by mauritsvanrees — CHANGES_REQUESTED** [review]
Can you put `wheel` at the top of the list? Otherwise I fear it will not be available to pip until it is too late. I must say I am not 100 percent sure putting it at the top actually helps, or that it only helps for a completely new invocation of pip.

**Comment by stevepiercy** [comment]
From https://pip.pypa.io/en/stable/cli/pip_install/#installation-order

> As of v6.1.0, pip installs dependencies before their dependents, i.e. in “topological order.” This is the only commitment pip currently makes related to order. While it may be coincidentally true that pip will install things in the order of the install arguments or in the order of the items in a requirements file, this is not a promise.

Thus if wheel is a dependency of any of the other requirements (it most likely is not) then wheel will get installed first.

Nonetheless putting it first is not a guarantee that it will be installed first. One way to guarantee order is to iterate over the requirements file, and call `pip install` on each line. But that feels like overkill to me.

Is there some other way to guarantee that wheel gets installed before the packages that might not have a wheel?

**Comment by mauritsvanrees** [comment]
Have an `initial-requirements.txt` file (or similar) with these (plus pins) to get the "packaging build system" up to full strength:

```
pip
setuptools
wheel
```

**Comment by stevepiercy** [comment]
I assume that I should also use two `pip install`s, one for each requirements files, to ensure that the requirements are installed in order of each file. If not, please let me know.

**Comment by stevepiercy** [comment]
> Have an `initial-requirements.txt` file (or similar) with these (plus pins) to get the "packaging build system" up to full strength:
> 
> ```
> pip
> setuptools
> wheel
> ```

Done in https://github.com/plone/documentation/pull/1398/commits/65e969963174e3af56a61bc2bad074f47613babb

**Comment by stevepiercy** [comment]
Could I get an approval from someone?

**Review by davisagli — APPROVED** [review]

**Pull request merged**
