### PR TITLE
improve resource registry documentation

### PR DESCRIPTION
**Pull request by frisi**
add an example of how to build an optimized bundle that combines resources of different addons
(see https://github.com/plone/Products.CMFPlone/issues/1163 for a discussion)

WIP - see questions marked with XXX

### CODE REVIEW

**Comment by frisi** [comment]
i'm not really sure if this proposal will be completely superseded by #518 or if it still has its right to exist.

as @cewing correctly stated in https://github.com/plone/documentation/pull/518#issuecomment-184044855  there are some open questions here and the procedure has to be tested and verified.
thanks for your effort btw - i can imagine that this overhaul was a lot of work (as this tiny PR took me hours to complete)

i'll probably try both out when https://github.com/plone/Products.CMFPlone/pull/1300 got merged and see if there is any drawback of [PLIP 1277](https://github.com/plone/Products.CMFPlone/issues/1277) compared to this proposal.

if anyone wants to step in in the meantime - you're very welcome ;-)

**Comment by svx** [comment]
What is the status here ?

**Comment by frisi** [comment]
@svx still the same state as described in https://github.com/plone/documentation/pull/482#issuecomment-186159634
i won't have time to try this out in the next months i think.

**Comment by svx** [comment]
@frisi ping ! :)

**Comment by pbauer** [comment]
@frisi ping!

**Comment by pbauer** [comment]
@ebrehault Is this still needed after we have https://docs.plone.org/adapt-and-extend/theming/resourceregistry.html#aggregate-bundles-for-production?

**Comment by frisi** [comment]
@pbauer and @svx sorry for being unresponsive in this ticket.
unfortunately after ploneconf in bucharest  i did not touch the plone5 resource registry stuff again. so i won't be able to give valuable feedback to this pr anytime soon :-(

**Comment by svx** [comment]
@frisi are you OK with closing this PR ?

We can try to fix or close, this is now open for quite some time :)

**Comment by frisi** [comment]
> unfortunately after ploneconf in bucharest i did not touch the plone5 resource registry stuff again. so i won't be able to give valuable feedback to this pr anytime soon :-(

still the same - so i'm ok to close this.

**Pull request closed without merging**
