### PR TITLE
reworked/ modernized whole contribution to core process to reflect status quo

### PR DESCRIPTION
**Pull request by jensens**
Please review! @tisto also interesting for you I guess.

### CODE REVIEW

**Comment by jensens** [comment]
btw, this is WIP, do not merge now!

**Comment by svx** [comment]
Thanks for all you work !

Maybe there is another solution, since we have already docs in buildout.coredev we had the idea to 'fetch' these and include them into the documentation, with doing this we would make sure that we have them always up 2 date.
If we would do that, we have to figure out how to deal with different version, but I guess that would be doable. 
A big plus would be we do not have to update the docs about development in different places.

**Comment by gforcada** [comment]
@svx buildout.coredev has also branches, so just pick the right branch for it, wouldn't that be enough?

**Comment by svx** [comment]
@gforcada yes that would work !

**Comment by polyester** [comment]
closing; this is fixed in 5.0 branch by using coredev.buildout directly; not worth the effort to fix up the 4.x branch.

**Pull request closed without merging**
